"use client";
import { useCallback,useEffect,useMemo,useRef,useState } from "react";
import { Archive,ArrowLeft,Copy,Download,File,Folder,FolderPlus,HardDrive,Move,Pencil,Plus,RefreshCcw,Trash2,Upload } from "lucide-react";
import { toast } from "sonner";
import { browserApiRequest } from "@/lib/api/browser-api";
import type { DockerBrowse,DockerEntry,DockerVolume } from "@/types/admin-docker-file-manager";
const btn="inline-flex h-10 items-center gap-2 rounded-xl border border-white/10 px-3 text-sm text-zinc-300 hover:bg-white/5 disabled:opacity-40";
export function DockerFileManager(){
 const [volumes,setVolumes]=useState<DockerVolume[]>([]),[volume,setVolume]=useState(""),[path,setPath]=useState(""),[entries,setEntries]=useState<DockerEntry[]>([]),[selected,setSelected]=useState<DockerEntry|null>(null),[busy,setBusy]=useState(false); const fileRef=useRef<HTMLInputElement>(null);
 const loadVolumes=useCallback(async()=>{const r=await browserApiRequest<{items:DockerVolume[]}>("/api/admin/docker-file-manager/volumes");setVolumes(r.items);setVolume(v=>v&&r.items.some(x=>x.name===v)?v:r.items[0]?.name||"")},[]);
 const browse=useCallback(async(v=volume,p=path)=>{if(!v){setEntries([]);return}const r=await browserApiRequest<DockerBrowse>(`/api/admin/docker-file-manager/browse?volume=${encodeURIComponent(v)}&path=${encodeURIComponent(p)}`);setEntries(r.items);setSelected(null)},[volume,path]);
 useEffect(()=>{void loadVolumes().catch(e=>toast.error(e.message))},[loadVolumes]); useEffect(()=>{void browse(volume,path).catch(e=>toast.error(e.message))},[volume,path,browse]);
 const parent=useMemo(()=>path.split("/").filter(Boolean).slice(0,-1).join("/"),[path]);
 const action=async(fn:()=>Promise<unknown>,message:string)=>{setBusy(true);try{await fn();toast.success(message);await loadVolumes();await browse()}catch(e){toast.error(e instanceof Error?e.message:"Operación fallida") }finally{setBusy(false)}};
 const createVolume=()=>{const name=window.prompt("Nombre del nuevo volumen Docker:");if(name)void action(()=>browserApiRequest("/api/admin/docker-file-manager/volumes",{method:"POST",body:JSON.stringify({name,driver:"local",labels:{"tryon.managed":"true"}})}),"Volumen creado.")};
 const createFolder=()=>{const name=window.prompt("Nombre de la carpeta:");if(name)void action(()=>browserApiRequest("/api/admin/docker-file-manager/directories",{method:"POST",body:JSON.stringify({volume,path:[path,name].filter(Boolean).join("/"),parents:true})}),"Carpeta creada.")};
 const removeSelected=()=>selected&&window.confirm(`¿Eliminar ${selected.name}?`)&&void action(()=>browserApiRequest(`/api/admin/docker-file-manager/paths?volume=${encodeURIComponent(volume)}&path=${encodeURIComponent(selected.path)}`,{method:"DELETE"}),"Elemento eliminado.");
 const upload=async(files:FileList|null)=>{if(!files?.length)return;setBusy(true);try{for(const file of Array.from(files)){const form=new FormData();form.set("volume",volume);form.set("path",[path,file.name].filter(Boolean).join("/"));form.set("overwrite","true");form.set("file",file);await browserApiRequest("/api/admin/docker-file-manager/upload",{method:"POST",body:form})}toast.success("Archivo(s) subidos.");await browse()}catch(e){toast.error(e instanceof Error?e.message:"No fue posible subir") }finally{setBusy(false);if(fileRef.current)fileRef.current.value=""}};
 const download=()=>{if(selected?.type!=="file")return;window.location.href=`/api/admin/docker-file-manager/download?volume=${encodeURIComponent(volume)}&path=${encodeURIComponent(selected.path)}`};

 const renameSelected=()=>{if(!selected)return;const name=window.prompt("Nuevo nombre:",selected.name);if(name&&name!==selected.name)void action(()=>browserApiRequest("/api/admin/docker-file-manager/rename",{method:"POST",body:JSON.stringify({volume,path:selected.path,new_name:name})}),"Elemento renombrado.")};
 const crumbs=useMemo(()=>{const parts=path.split("/").filter(Boolean);return [{label:volume,path:""},...parts.map((part,index)=>({label:part,path:parts.slice(0,index+1).join("/")}))]},[volume,path]);
 const transfer=(operation:"copy"|"move")=>{if(!selected)return;const destination=window.prompt(`Ruta destino para ${operation==="copy"?"copiar":"mover"}:`,selected.path);if(destination)void action(()=>browserApiRequest("/api/admin/docker-file-manager/transfer",{method:"POST",body:JSON.stringify({source_volume:volume,source_path:selected.path,destination_volume:volume,destination_path:destination,overwrite:false,operation})}),operation==="copy"?"Elemento copiado.":"Elemento movido.")};
 return <div className="space-y-5"><section className="luxia-panel rounded-3xl p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex gap-4"><div className="flex size-14 items-center justify-center rounded-2xl border border-red-500/20 bg-red-950/25 text-red-400"><HardDrive/></div><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-red-500">Infraestructura Docker</p><h1 className="mt-2 text-2xl font-semibold text-white">Docker File Manager</h1><p className="mt-2 text-sm text-zinc-500">Administra volúmenes y archivos sin copiar el volumen completo al host.</p></div></div><div className="flex gap-2"><button className={btn} onClick={()=>void loadVolumes()}><RefreshCcw size={15}/>Actualizar</button><button className="luxia-red-glow inline-flex h-10 items-center gap-2 rounded-xl bg-red-700 px-3 text-sm font-semibold text-white" onClick={createVolume}><Plus size={15}/>Crear volumen</button></div></div></section>
 <section className="grid gap-5 xl:grid-cols-[300px_1fr]"><aside className="luxia-panel rounded-3xl p-4"><h2 className="mb-3 text-sm font-semibold text-white">Volúmenes Docker</h2><div className="space-y-2">{volumes.map(v=><button key={v.name} onClick={()=>{setVolume(v.name);setPath("")}} className={`w-full rounded-xl border p-3 text-left ${volume===v.name?"border-red-500/30 bg-red-950/20":"border-white/7 bg-black/20"}`}><div className="flex items-center gap-2 text-sm text-white"><Archive size={15}/>{v.name}</div><div className="mt-1 text-xs text-zinc-600">{v.driver}</div></button>)}</div>{volume&&<button disabled={busy} onClick={()=>window.confirm(`¿Eliminar el volumen ${volume}?`)&&void action(()=>browserApiRequest(`/api/admin/docker-file-manager/volumes/${encodeURIComponent(volume)}?force=false`,{method:"DELETE"}),"Volumen eliminado.")} className="mt-4 inline-flex items-center gap-2 text-sm text-red-400"><Trash2 size={14}/>Eliminar volumen</button>}</aside>
 <main className="luxia-panel rounded-3xl p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2 text-sm text-zinc-400"><button disabled={!path} onClick={()=>setPath(parent)} className={btn}><ArrowLeft size={15}/></button><div className="flex flex-wrap items-center gap-1">{crumbs.map((crumb,index)=><span key={`${crumb.path}-${index}`} className="flex items-center gap-1"><button onClick={()=>setPath(crumb.path)} className="rounded-lg px-2 py-1 text-zinc-300 hover:bg-white/5">{crumb.label||"Sin volumen"}</button>{index<crumbs.length-1&&<span className="text-zinc-700">/</span>}</span>)}</div></div><div className="flex flex-wrap gap-2"><button disabled={!volume||busy} className={btn} onClick={createFolder}><FolderPlus size={15}/>Carpeta</button><button disabled={!volume||busy} className={btn} onClick={()=>fileRef.current?.click()}><Upload size={15}/>Subir</button><input ref={fileRef} hidden type="file" multiple onChange={e=>void upload(e.target.files)}/><button disabled={!selected} className={btn} onClick={renameSelected}><Pencil size={15}/>Renombrar</button><button disabled={!selected} className={btn} onClick={()=>transfer("copy")}><Copy size={15}/>Copiar</button><button disabled={!selected} className={btn} onClick={()=>transfer("move")}><Move size={15}/>Mover</button><button disabled={selected?.type!=="file"} className={btn} onClick={download}><Download size={15}/>Descargar</button><button disabled={!selected} className={btn} onClick={removeSelected}><Trash2 size={15}/>Eliminar</button></div></div>
 <div className="mt-5 overflow-hidden rounded-2xl border border-white/8"><div className="grid grid-cols-[1fr_120px_150px] bg-white/[.03] px-4 py-3 text-xs uppercase tracking-wide text-zinc-600"><span>Nombre</span><span>Tipo</span><span>Tamaño</span></div>{entries.length===0?<div className="py-16 text-center text-zinc-600">Carpeta vacía</div>:entries.map(item=><button key={item.path} onDoubleClick={()=>item.type==="directory"&&setPath(item.path)} onClick={()=>setSelected(item)} className={`grid w-full grid-cols-[1fr_120px_150px] items-center border-t border-white/5 px-4 py-3 text-left text-sm ${selected?.path===item.path?"bg-red-950/20":"hover:bg-white/[.02]"}`}><span className="flex items-center gap-2 text-zinc-200">{item.type==="directory"?<Folder size={16} className="text-amber-300"/>:<File size={16} className="text-zinc-500"/>}{item.name}</span><span className="text-zinc-500">{item.type}</span><span className="text-zinc-500">{item.type==="directory"?"—":`${(item.size/1024/1024).toFixed(2)} MB`}</span></button>)}</div>{selected&&<div className="mt-4 grid gap-3 rounded-2xl border border-white/8 bg-black/20 p-4 text-sm sm:grid-cols-3"><div><p className="text-xs uppercase text-zinc-600">Seleccionado</p><p className="mt-1 break-all text-zinc-200">{selected.name}</p></div><div><p className="text-xs uppercase text-zinc-600">Ruta</p><p className="mt-1 break-all text-zinc-400">{selected.path}</p></div><div><p className="text-xs uppercase text-zinc-600">Tamaño</p><p className="mt-1 text-zinc-400">{selected.type==="directory"?"Carpeta":`${(selected.size/1024/1024).toFixed(2)} MB`}</p></div></div>}</main></section></div>}
