"use client";
import {useCallback,useEffect,useState} from "react";
import {Banknote,Boxes,RefreshCcw,ShieldCheck,WalletCards,X,RotateCcw} from "lucide-react";
import type {LucideIcon} from "lucide-react";
import {toast} from "sonner";
import {browserApiRequest} from "@/lib/api/browser-api";
import type {BagDetail,CashboxSummary,ExpirationSettings,TokenBag,TokenBagList,Withdrawal} from "@/types/finance-cashbox";
const money=(v:number)=>`USD ${Number(v||0).toFixed(6)}`;
const date=(v?:string|null)=>v?new Intl.DateTimeFormat("es-MX",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—";
const labels:Record<string,string>={new:"Nueva",active:"Activa",exhausted:"Agotada",expired:"Expirada",refunded:"Reembolsada"};
export default function CashboxPage(){
 const [summary,setSummary]=useState<CashboxSummary|null>(null),[bags,setBags]=useState<TokenBag[]>([]),[withdrawals,setWithdrawals]=useState<Withdrawal[]>([]),[expiry,setExpiry]=useState<ExpirationSettings>({enabled:true,days:730}),[detail,setDetail]=useState<BagDetail|null>(null),[loading,setLoading]=useState(true),[status,setStatus]=useState("");
 const [amount,setAmount]=useState(""),[concept,setConcept]=useState("Retiro de utilidad"),[beneficiary,setBeneficiary]=useState(""),[action,setAction]=useState<string|null>(null);
 const summaryCards: Array<{label:string;value:number;icon:LucideIcon;className:string}> = summary ? [
  {label:"Puedes retirar",value:summary.available_usd,icon:WalletCards,className:"text-emerald-300"},
  {label:"Protegido para IA",value:summary.protected_infrastructure_usd,icon:ShieldCheck,className:"text-sky-300"},
  {label:"Utilidad bloqueada",value:summary.blocked_profit_usd,icon:Boxes,className:"text-amber-300"},
  {label:"Retiros registrados",value:summary.withdrawals_usd,icon:Banknote,className:"text-rose-300"},
 ] : [];
 const load=useCallback(async()=>{setLoading(true);try{const q=status?`?status=${status}`:"";const [s,b,w,e]=await Promise.all([browserApiRequest<CashboxSummary>("/api/admin/finances/cashbox"),browserApiRequest<TokenBagList>(`/api/admin/finances/token-bags${q}`),browserApiRequest<Withdrawal[]>("/api/admin/finances/withdrawals"),browserApiRequest<ExpirationSettings>("/api/admin/finances/token-bag-expiration")]);setSummary(s);setBags(b.items);setWithdrawals(w);setExpiry(e);}catch(e){toast.error(e instanceof Error?e.message:"No fue posible cargar la caja.")}finally{setLoading(false)}},[status]);
 useEffect(()=>{void load()},[load]);
 async function openBag(id:number){try{setDetail(await browserApiRequest<BagDetail>(`/api/admin/finances/token-bags/${id}`))}catch(e){toast.error(e instanceof Error?e.message:"No fue posible abrir la bolsa.")}}
 async function saveExpiry(){try{const r=await browserApiRequest<ExpirationSettings>("/api/admin/finances/token-bag-expiration",{method:"PUT",body:JSON.stringify(expiry)});setExpiry(r);toast.success("Caducidad guardada. Solo las bolsas futuras toman la nueva vigencia; las existentes conservan su fecha.");void load()}catch(e){toast.error(e instanceof Error?e.message:"No fue posible guardar.")}}
 async function withdraw(){const n=Number(amount);if(!Number.isFinite(n)||n<=0){toast.error("Escribe un importe válido.");return}if(!confirm(`Registrar retiro de ${money(n)}?`))return;try{await browserApiRequest("/api/admin/finances/withdrawals",{method:"POST",body:JSON.stringify({amount_usd:n,concept,beneficiary:beneficiary||null})});toast.success("Retiro registrado y descontado de la caja.");setAmount("");void load()}catch(e){toast.error(e instanceof Error?e.message:"No fue posible registrar el retiro.")}}
 async function reconcile(){if(!detail?.purchase_id)return;setAction("reconcile");try{await browserApiRequest(`/api/admin/token-purchases/${detail.purchase_id}/reconcile`,{method:"POST",body:JSON.stringify({force:false})});toast.success("Pago conciliado con Stripe.");setDetail(await browserApiRequest<BagDetail>(`/api/admin/finances/token-bags/${detail.bag.id}`));void load()}catch(e){toast.error(e instanceof Error?e.message:"No fue posible conciliar.")}finally{setAction(null)}}
 async function refund(){if(!detail?.purchase_id||!detail.bag.refundable)return;if(!confirm("Esta operación reembolsará la compra y retirará los tokens de la bolsa. ¿Continuar?"))return;setAction("refund");try{await browserApiRequest(`/api/admin/token-purchases/${detail.purchase_id}/refund`,{method:"POST",body:JSON.stringify({amount:null,reason:"requested_by_customer",remove_tokens:true})});toast.success("Reembolso solicitado correctamente.");setDetail(null);void load()}catch(e){toast.error(e instanceof Error?e.message:"No fue posible reembolsar.")}finally{setAction(null)}}
 return <main className="space-y-6">
  <section className="luxia-panel rounded-3xl p-6"><div className="flex items-center justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-emerald-400">Caja registradora</p><h1 className="mt-2 text-2xl font-semibold text-white">Dinero disponible, protegido y bloqueado</h1><p className="mt-3 max-w-4xl text-sm leading-7 text-zinc-500">La caja descuenta retiros registrados. El dinero protegido corresponde a tokens vigentes; no debe usarse para gastos personales.</p></div><button onClick={()=>void load()} className="rounded-xl border border-white/10 p-3 text-zinc-400 hover:text-white"><RefreshCcw size={18}/></button></div></section>
  {loading?<div className="luxia-panel rounded-3xl p-10 text-center text-zinc-500">Calculando la caja…</div>:summary&&<section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{summaryCards.map(({label,value,icon:Icon,className})=><article key={label} className="luxia-panel rounded-3xl p-5"><Icon className={className} size={20}/><p className="mt-5 text-xs uppercase tracking-widest text-zinc-600">{label}</p><p className={`mt-2 text-2xl font-semibold ${className}`}>{money(value)}</p></article>)}</section>}
  <section className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><article className="luxia-panel rounded-3xl p-6"><h2 className="text-lg font-semibold text-white">Registrar retiro</h2><p className="mt-2 text-sm text-zinc-500">Nunca permite retirar más que la caja disponible.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><input value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Importe USD" type="number" step="0.01" className="h-11 rounded-xl border border-white/10 bg-black/30 px-4 text-white"/><input value={beneficiary} onChange={e=>setBeneficiary(e.target.value)} placeholder="Beneficiario" className="h-11 rounded-xl border border-white/10 bg-black/30 px-4 text-white"/><input value={concept} onChange={e=>setConcept(e.target.value)} placeholder="Concepto" className="h-11 rounded-xl border border-white/10 bg-black/30 px-4 text-white sm:col-span-2"/></div><button onClick={withdraw} className="mt-4 rounded-xl bg-emerald-500 px-5 py-3 text-sm font-semibold text-black">Registrar retiro</button><div className="mt-6 space-y-2">{withdrawals.slice(0,6).map(w=><div key={w.id} className="flex justify-between rounded-xl border border-white/6 p-3 text-sm"><span className="text-zinc-400">{w.concept}<small className="ml-2 text-zinc-700">{date(w.withdrawn_at)}</small></span><b className="text-rose-300">-{money(w.amount_usd)}</b></div>)}</div></article>
  <article className="luxia-panel rounded-3xl p-6"><h2 className="text-lg font-semibold text-white">Caducidad de bolsas</h2><p className="mt-2 text-sm leading-6 text-zinc-500">Al expirar, los tokens restantes se marcan como expirados y su saldo económico se libera a la caja. No se registran como generaciones falsas.</p><label className="mt-5 flex items-center gap-3 text-sm text-zinc-300"><input type="checkbox" checked={expiry.enabled} onChange={e=>setExpiry({...expiry,enabled:e.target.checked})}/>Habilitar caducidad</label><input value={expiry.days} onChange={e=>setExpiry({...expiry,days:Number(e.target.value)})} type="number" min={1} max={3650} className="mt-4 h-11 w-full rounded-xl border border-white/10 bg-black/30 px-4 text-white"/><p className="mt-2 text-xs text-zinc-600">Ejemplo: 730 días = 2 años; 1095 días = 3 años.</p><button onClick={saveExpiry} className="mt-4 rounded-xl border border-white/10 px-5 py-3 text-sm text-white">Guardar configuración</button></article></section>
  <section className="luxia-panel rounded-3xl p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold text-white">Bolsas de tokens</h2><p className="mt-2 text-sm text-zinc-500">Estado de cuenta de cada compra, plan o paquete.</p></div><select value={status} onChange={e=>setStatus(e.target.value)} className="h-10 rounded-xl border border-white/10 bg-black px-3 text-sm text-white"><option value="">Todos los estados</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div className="mt-5 overflow-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="text-xs uppercase text-zinc-600"><tr>{["Bolsa","Usuario","Origen","Estado","Tokens","Cobrado","Utilidad","Infraestructura protegida","Expira","Acción"].map(x=><th key={x} className="border-b border-white/6 px-3 py-3">{x}</th>)}</tr></thead><tbody>{bags.map(b=><tr key={b.id} className="border-b border-white/5 text-zinc-300"><td className="px-3 py-4">#{b.id}</td><td className="px-3 py-4">{b.user_email||`#${b.user_id}`}</td><td className="px-3 py-4">{b.source_label}</td><td className="px-3 py-4">{labels[b.status]||b.status}</td><td className="px-3 py-4">{b.remaining_tokens}/{b.original_tokens}</td><td className="px-3 py-4">{money(b.amount_paid_usd)}</td><td className="px-3 py-4 text-emerald-300">{money(b.commercial_profit_released_usd)}</td><td className="px-3 py-4 text-sky-300">{money(b.protected_infrastructure_remaining_usd)}</td><td className="px-3 py-4">{date(b.expires_at)}</td><td className="px-3 py-4"><button onClick={()=>void openBag(b.id)} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-white">Ver detalle</button></td></tr>)}</tbody></table></div></section>
  {detail&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4"><article className="max-h-[94vh] w-full max-w-6xl overflow-auto rounded-3xl border border-white/10 bg-[#09090a] p-6"><header className="flex justify-between"><div><p className="text-xs uppercase tracking-widest text-sky-400">Bolsa #{detail.bag.id}</p><h2 className="mt-2 text-2xl font-semibold text-white">{detail.bag.source_label}</h2></div><button onClick={()=>setDetail(null)}><X className="text-zinc-400"/></button></header><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Cliente pagó",detail.bag.amount_paid_usd],["Utilidad total",detail.bag.commercial_profit_total_usd],["Utilidad liberada",detail.bag.commercial_profit_released_usd],["Infraestructura restante",detail.bag.protected_infrastructure_remaining_usd],["Valor por token",detail.bag.effective_token_value_usd],["Ganancia por token",detail.bag.effective_profit_per_token_usd],["Infraestructura por token",detail.bag.infrastructure_capacity_per_token_usd],["Redondeos",detail.bag.rounding_surplus_usd]].map(([l,v])=><div key={String(l)} className="rounded-2xl border border-white/6 p-4"><p className="text-xs text-zinc-600">{String(l)}</p><p className="mt-2 font-semibold text-white">{money(Number(v))}</p></div>)}</div><div className="mt-6 rounded-2xl border border-white/6 p-4"><p className="text-sm text-zinc-400">Estado de reembolso</p><p className={`mt-2 font-semibold ${detail.bag.refundable?"text-emerald-300":"text-amber-300"}`}>{detail.bag.refund_reason}</p><div className="mt-4 flex gap-3"><button disabled={!detail.purchase_id||action!==null} onClick={reconcile} className="flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2 text-sm text-white"><RotateCcw size={15}/>Conciliar con Stripe</button><button disabled={!detail.bag.refundable||!detail.purchase_id||action!==null} onClick={refund} className="rounded-xl bg-rose-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">Reembolsar</button></div></div><h3 className="mt-7 font-semibold text-white">Generaciones pagadas con esta bolsa</h3><div className="mt-3 overflow-auto"><table className="w-full text-sm"><thead className="text-zinc-600"><tr><th className="p-2 text-left">Generación</th><th>Tokens</th><th>Infraestructura</th><th>Ganancia</th><th>Fecha</th></tr></thead><tbody>{detail.generations.map(g=><tr key={g.execution_id} className="border-t border-white/5"><td className="p-2 text-zinc-300">{g.execution_id.slice(0,8)}</td><td className="text-center">{g.tokens_used}</td><td className="text-center">{money(g.infrastructure_cost_usd)}</td><td className="text-center">{money(g.company_profit_usd)}</td><td className="text-center">{date(g.created_at)}</td></tr>)}</tbody></table></div></article></div>}
 </main>
}
