"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { BadgeDollarSign,RefreshCcw,Search } from "lucide-react";
import { browserApiRequest } from "@/lib/api/browser-api";

type FinanceItem={execution_id:string;generation_module_id:number|null;module_key:string;user_id:number|null;status:string;tokens_consumed:number;recognized_revenue_usd:number;infrastructure_cost_usd:number;gross_profit_usd:number;gross_margin_percent:number|null;traceability_status:string;breakdown:Record<string,unknown>;created_at:string};
type Response={items:FinanceItem[];total:number;skip:number;limit:number;summary:{total_generations:number;recognized_revenue_usd:number;infrastructure_cost_usd:number;gross_profit_usd:number;exact_records:number;partial_records:number;unavailable_records:number}};
const usd=(n:number)=>new Intl.NumberFormat("es-MX",{style:"currency",currency:"USD",minimumFractionDigits:2,maximumFractionDigits:6}).format(n);
export default function GenerationFinancesPage(){
 const [data,setData]=useState<Response|null>(null); const [status,setStatus]=useState(""); const [trace,setTrace]=useState(""); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [selected,setSelected]=useState<FinanceItem|null>(null);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{const p=new URLSearchParams({limit:"500"});if(status)p.set("status",status);if(trace)p.set("traceability",trace);setData(await browserApiRequest<Response>(`/api/admin/finances/generations?${p}`));}catch(e){setError(e instanceof Error?e.message:"No fue posible cargar finanzas.");}finally{setLoading(false)}},[status,trace]);
 useEffect(()=>{void load()},[load]); const s=data?.summary;
 const cards=useMemo(()=>[{l:"Ingreso reconocido",v:usd(s?.recognized_revenue_usd??0)},{l:"Infraestructura",v:usd(s?.infrastructure_cost_usd??0)},{l:"Ganancia bruta",v:usd(s?.gross_profit_usd??0)},{l:"Generaciones",v:String(s?.total_generations??0)}],[s]);
 return <div className="space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-semibold text-white">Finanzas por generación</h1><p className="text-sm text-zinc-400">Ingreso real atribuido por lotes FIFO, costo de infraestructura y ganancia.</p></div><button onClick={()=>void load()} className="rounded-xl border border-white/10 px-4 py-2 text-sm text-zinc-200"><RefreshCcw className="mr-2 inline h-4 w-4"/>Actualizar</button></div>
 <div className="grid gap-4 md:grid-cols-4">{cards.map(c=><div key={c.l} className="rounded-2xl border border-white/10 bg-zinc-950 p-5"><p className="text-xs uppercase text-zinc-500">{c.l}</p><p className="mt-2 text-2xl font-semibold text-white">{c.v}</p></div>)}</div>
 <div className="flex gap-3 rounded-2xl border border-white/10 bg-zinc-950 p-4"><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-lg bg-zinc-900 px-3 py-2 text-sm text-white"><option value="">Todos los estados</option><option value="completed">Completadas</option><option value="cancelled">Canceladas</option><option value="failed">Fallidas</option></select><select value={trace} onChange={e=>setTrace(e.target.value)} className="rounded-lg bg-zinc-900 px-3 py-2 text-sm text-white"><option value="">Toda trazabilidad</option><option value="exact">Exacta</option><option value="partial">Parcial / saldo anterior</option><option value="unavailable">No disponible</option></select></div>
 {error&&<div className="rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-red-300">{error}</div>}
 <div className="overflow-hidden rounded-2xl border border-white/10 bg-zinc-950"><table className="w-full text-sm"><thead className="bg-white/5 text-left text-zinc-400"><tr><th className="p-3">Ejecución</th><th>Módulo</th><th>Estado</th><th>Tokens</th><th>Ingreso</th><th>Infraestructura</th><th>Ganancia</th><th>Trazabilidad</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan={9} className="p-8 text-center text-zinc-500">Cargando…</td></tr>:data?.items.map(i=><tr key={i.execution_id} className="border-t border-white/5 text-zinc-300"><td className="p-3 font-mono text-xs">{i.execution_id.slice(0,8)}</td><td>{i.module_key}</td><td>{i.status}</td><td>{i.tokens_consumed}</td><td>{usd(i.recognized_revenue_usd)}</td><td>{usd(i.infrastructure_cost_usd)}</td><td className={i.gross_profit_usd<0?"text-red-300":"text-emerald-300"}>{usd(i.gross_profit_usd)}</td><td>{i.traceability_status}</td><td><button onClick={()=>setSelected(i)} className="px-3 py-2 text-blue-300">Detalle</button></td></tr>)}</tbody></table></div>
 {selected&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-6" onClick={()=>setSelected(null)}><div className="max-h-[85vh] w-full max-w-3xl overflow-auto rounded-2xl border border-white/10 bg-zinc-950 p-6" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between"><h2 className="text-xl font-semibold text-white">Desglose financiero</h2><button onClick={()=>setSelected(null)} className="text-zinc-400">Cerrar</button></div><pre className="mt-4 whitespace-pre-wrap rounded-xl bg-black p-4 text-xs text-zinc-300">{JSON.stringify(selected.breakdown,null,2)}</pre></div></div>}
 </div>}
