"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Calculator, Copy, LoaderCircle, Search, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { browserApiRequest } from "@/lib/api/browser-api";
import type { AppliedPricingRuleResponse, PricingSimulatorRecommendation, PricingSimulatorResponse } from "@/types/admin-pricing-coupons";

const money = (v:number) => `USD ${v.toFixed(6).replace(/0+$/,"").replace(/\.$/,"")}`;
const inputClass="h-11 w-full rounded-xl border border-white/8 bg-[#09090a] px-3 text-sm text-white outline-none focus:border-sky-500/30";

export default function ProfitSimulatorPage(){
 const [modules,setModules]=useState<AppliedPricingRuleResponse[]>([]); const [moduleId,setModuleId]=useState("");
 const [durationMode,setDurationMode]=useState("historical"); const [manualDuration,setManualDuration]=useState("120");
 const [tokenValue,setTokenValue]=useState(""); const [profitPerToken,setProfitPerToken]=useState(""); const [simulationDiscount,setSimulationDiscount]=useState("15");
 const [targetProfit,setTargetProfit]=useState("1"); const [minTokens,setMinTokens]=useState("8"); const [maxTokens,setMaxTokens]=useState("12"); const [worstDiscount,setWorstDiscount]=useState("15");
 const [simulation,setSimulation]=useState<PricingSimulatorResponse|null>(null); const [recommendations,setRecommendations]=useState<PricingSimulatorResponse|null>(null);
 const [simLoading,setSimLoading]=useState(false); const [searchLoading,setSearchLoading]=useState(false);
 useEffect(()=>{void browserApiRequest<AppliedPricingRuleResponse[]>("/api/admin/applied-pricing-rules").then(rows=>{const configured=rows.filter(r=>r.configured);setModules(configured);if(configured[0])setModuleId(String(configured[0].generation_module_id));}).catch(e=>toast.error(e instanceof Error?e.message:"No fue posible cargar los módulos."));},[]);
 const selected=useMemo(()=>modules.find(r=>String(r.generation_module_id)===moduleId),[modules,moduleId]);
 useEffect(()=>{if(selected){setTokenValue(String(selected.token_value_usd));setProfitPerToken(String(selected.desired_profit_per_token_usd));setSimulation(null);setRecommendations(null);}},[selected]);
 const common=()=>({generation_module_id:Number(moduleId),duration_mode:durationMode,manual_duration_seconds:durationMode==="manual"?Number(manualDuration):null});
 async function simulate(e:FormEvent){e.preventDefault();const tv=Number(tokenValue),p=Number(profitPerToken),d=Number(simulationDiscount);if(!moduleId||tv<=0||p<0||p>=tv){toast.error("La ganancia por token debe ser menor que el valor del token.");return;}setSimLoading(true);try{setSimulation(await browserApiRequest<PricingSimulatorResponse>("/api/admin/profit-simulator/simulate",{method:"POST",body:JSON.stringify({...common(),token_value_usd:tv,desired_profit_per_token_usd:p,scenarios:[{label:"Sin descuento",discount_percent:0},{label:"Descuento probado",discount_percent:d}],worst_discount_percent:d})}));}catch(e){toast.error(e instanceof Error?e.message:"No fue posible simular.");}finally{setSimLoading(false)}}
 async function search(e:FormEvent){e.preventDefault();setSearchLoading(true);try{setRecommendations(await browserApiRequest<PricingSimulatorResponse>("/api/admin/profit-simulator/recommendations",{method:"POST",body:JSON.stringify({...common(),target_profit_usd:Number(targetProfit),target_tokens_min:Number(minTokens),target_tokens_max:Number(maxTokens),worst_discount_percent:Number(worstDiscount)})}));}catch(e){toast.error(e instanceof Error?e.message:"No fue posible buscar recomendaciones.");}finally{setSearchLoading(false)}}
 function useRecommendation(r:PricingSimulatorRecommendation){setTokenValue(String(r.token_value_usd));setProfitPerToken(String(r.desired_profit_per_token_usd));setSimulationDiscount(String(r.worst_discount_percent));window.scrollTo({top:0,behavior:"smooth"});toast.success("Valores copiados a la simulación.");}
 return <div className="space-y-5">
  <section className="luxia-panel rounded-3xl p-6"><div className="flex items-start gap-4"><div className="flex size-14 items-center justify-center rounded-2xl border border-sky-500/20 bg-sky-950/20 text-sky-300"><Calculator size={24}/></div><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-sky-400">Herramienta de decisión</p><h1 className="mt-2 text-2xl font-semibold text-white">Simulador de ganancias</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-zinc-500">Prueba valores concretos o pide recomendaciones para alcanzar una ganancia objetivo. Nada se guarda ni modifica tus reglas.</p></div></div>
   <div className="mt-6 grid gap-4 md:grid-cols-3"><Field label="Módulo a analizar"><select className={inputClass} value={moduleId} onChange={e=>setModuleId(e.target.value)}><option value="">Selecciona</option>{modules.map(m=><option key={m.generation_module_id} value={m.generation_module_id}>{m.module_name}</option>)}</select></Field><Field label="Tiempo de referencia"><select className={inputClass} value={durationMode} onChange={e=>setDurationMode(e.target.value)}><option value="historical">Historial del módulo</option><option value="initial">Tiempo inicial</option><option value="manual">Tiempo manual</option></select></Field>{durationMode==="manual"&&<Field label="Segundos manuales"><input className={inputClass} value={manualDuration} onChange={e=>setManualDuration(e.target.value)}/></Field>}</div>
   {selected&&<div className="mt-4 grid gap-3 md:grid-cols-4"><Metric label="Proveedor / GPU" value={`${selected.provider} · ${selected.gpu_key||"Sin GPU"}`}/><Metric label="Tiempo estimado actual" value={`${selected.estimated_duration_seconds.toFixed(1)} s`}/><Metric label="Historial usado" value={`${selected.historical_samples_used||0} generaciones`}/><Metric label="Costo GPU" value={`${money(selected.gpu_cost_usd_per_second||0)}/s`}/></div>}
  </section>
  <div className="grid gap-5 xl:grid-cols-2">
   <section className="luxia-panel rounded-3xl p-6"><h2 className="text-lg font-semibold text-white">¿Qué pasaría con mis valores?</h2><p className="mt-2 text-sm text-zinc-500">Introduce una configuración concreta y observa el resultado probable.</p><form onSubmit={simulate} className="mt-5 space-y-4"><Field label="Valor de 1 token (USD)"><input className={inputClass} value={tokenValue} onChange={e=>setTokenValue(e.target.value)}/></Field><Field label="Ganancia deseada por token (USD)"><input className={inputClass} value={profitPerToken} onChange={e=>setProfitPerToken(e.target.value)}/></Field><Field label="Descuento que quieres probar (%)"><input className={inputClass} value={simulationDiscount} onChange={e=>setSimulationDiscount(e.target.value)}/></Field><button disabled={simLoading} className="inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl border border-sky-500/20 bg-sky-950/20 text-sm font-semibold text-sky-200 disabled:opacity-50">{simLoading?<LoaderCircle className="animate-spin" size={16}/>:<Sparkles size={16}/>}Simular mis valores</button></form>{simulation&&<ScenarioResult result={simulation}/>}</section>
   <section className="luxia-panel rounded-3xl p-6"><h2 className="text-lg font-semibold text-white">Encuentra una configuración para tu objetivo</h2><p className="mt-2 text-sm text-zinc-500">Aquí no importan los valores del bloque izquierdo. Solo indica el resultado que quieres alcanzar.</p><form onSubmit={search} className="mt-5 space-y-4"><Field label="Quiero ganar aproximadamente por generación (USD)"><input className={inputClass} value={targetProfit} onChange={e=>setTargetProfit(e.target.value)}/></Field><Field label="Rango deseado de tokens"><div className="grid grid-cols-2 gap-2"><input className={inputClass} value={minTokens} onChange={e=>setMinTokens(e.target.value)} placeholder="Mínimo"/><input className={inputClass} value={maxTokens} onChange={e=>setMaxTokens(e.target.value)} placeholder="Máximo"/></div></Field><Field label="Peor descuento que debe soportar (%)"><input className={inputClass} value={worstDiscount} onChange={e=>setWorstDiscount(e.target.value)}/></Field><button disabled={searchLoading} className="inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl border border-emerald-500/20 bg-emerald-950/20 text-sm font-semibold text-emerald-200 disabled:opacity-50">{searchLoading?<LoaderCircle className="animate-spin" size={16}/>:<Search size={16}/>}Buscar configuraciones</button></form>{recommendations&&<RecommendationList result={recommendations} onUse={useRecommendation}/>}</section>
  </div>
 </div>
}
function ScenarioResult({result}:{result:PricingSimulatorResponse}){return <div className="mt-6 space-y-3"><div className="grid grid-cols-2 gap-2"><Metric label="Costo proveedor" value={money(result.infrastructure_cost_usd)}/><Metric label="Tiempo facturable" value={`${result.billable_seconds.toFixed(1)} s`}/></div>{result.scenarios.map(s=><div key={s.label} className="rounded-2xl border border-white/6 bg-black/20 p-4"><p className="font-semibold text-white">{s.label}</p><div className="mt-3 grid grid-cols-2 gap-2"><Metric label="Tokens" value={String(s.tokens)}/><Metric label="Cliente paga" value={money(s.customer_value_usd)}/><Metric label="Beneficio entregado" value={money(s.discount_given_usd)}/><Metric label="Tu ganancia" value={money(s.company_total_usd)}/></div></div>)}</div>}
function RecommendationList({result,onUse}:{result:PricingSimulatorResponse;onUse:(r:PricingSimulatorRecommendation)=>void}){return <div className="mt-6 space-y-3">{result.recommendations.length===0?<p className="rounded-xl border border-amber-500/15 bg-amber-950/10 p-4 text-sm text-amber-200">No se encontró una combinación. Amplía el rango de tokens o reduce la meta.</p>:result.recommendations.map((r,i)=><article key={`${r.token_value_usd}-${r.desired_profit_per_token_usd}-${i}`} className="rounded-2xl border border-white/6 bg-black/20 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs text-zinc-600">{i===0?"Recomendada":`Opción ${i+1}`}</p><p className="mt-1 font-semibold text-white">Token {money(r.token_value_usd)} · Ganancia/token {money(r.desired_profit_per_token_usd)}</p></div><span className="text-emerald-300">{r.tokens} tokens</span></div><div className="mt-3 grid grid-cols-2 gap-2"><Metric label="Ganancia estimada" value={money(r.estimated_company_profit_usd)}/><Metric label="Cliente paga" value={money(r.estimated_customer_value_usd)}/></div><button onClick={()=>onUse(r)} className="mt-3 inline-flex h-10 w-full items-center justify-center gap-2 rounded-xl border border-sky-500/20 text-sm text-sky-200"><Copy size={15}/>Probar esta opción</button></article>)}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-xs text-zinc-500">{label}</span>{children}</label>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-white/6 bg-black/20 p-3"><p className="text-[10px] text-zinc-600">{label}</p><p className="mt-1 text-sm font-semibold text-white">{value}</p></div>}
