"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Boxes, ChevronDown, ChevronUp, Code2, FileJson2, LoaderCircle, Play, Plus, RefreshCw, Save, Search, Square, Trash2, X } from "lucide-react";
import { toast } from "sonner";
import { browserApiRequest } from "@/lib/api/browser-api";
import type { GenerationExecutionEngine, GenerationModule, GenerationModuleInput, GenerationModuleListResponse, GenerationModuleOutput, WorkflowInputBinding, WorkflowOutputBinding, GenerationModuleExecution, GenerationRuntimeHealth } from "@/types/admin-generation-modules";

const inputTypes = ["image","file","text","integer","float","boolean","json"] as const;
const outputTypes = ["image","images","file","json","metadata"] as const;
const engines: {value: GenerationExecutionEngine; label: string}[] = [
  {value:"simulated", label:"Simulado"}, {value:"local_docker", label:"Docker local"}, {value:"runpod_serverless", label:"RunPod Serverless"},
];
const emptyInput = (position:number): GenerationModuleInput => ({key:`input_${position+1}`,name:"Nueva entrada",input_type:"image",position,is_required:true,validation:{}});
const emptyOutput = (position:number): GenerationModuleOutput => ({key:`output_${position+1}`,name:"Nueva salida",output_type:"image",position,is_required:true,metadata:{}});

export default function GenerationModulesPage() {
  const [items,setItems]=useState<GenerationModule[]>([]); const [selected,setSelected]=useState<GenerationModule|null>(null);
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [search,setSearch]=useState("");
  const [showCreate,setShowCreate]=useState(false); const [workflowModal,setWorkflowModal]=useState(false); const [pythonModal,setPythonModal]=useState(false);
  const load=useCallback(async()=>{setLoading(true);try{const q=new URLSearchParams({limit:"200"});if(search.trim())q.set("search",search.trim());const r=await browserApiRequest<GenerationModuleListResponse>(`/api/admin/generation-modules?${q}`);setItems(r.items);if(selected){setSelected(r.items.find(x=>x.id===selected.id)??null)}}catch(e){toast.error(e instanceof Error?e.message:"No fue posible cargar los módulos.")}finally{setLoading(false)}},[search,selected?.id]);
  useEffect(()=>{const t=setTimeout(()=>void load(),200);return()=>clearTimeout(t)},[load]);
  const save=async()=>{if(!selected)return;setSaving(true);try{const updated=await browserApiRequest<GenerationModule>(`/api/admin/generation-modules/${selected.id}`,{method:"PATCH",body:JSON.stringify({name:selected.name,description:selected.description,category:selected.category,default_execution_engine:selected.default_execution_engine,is_active:selected.is_active,inputs:selected.inputs.map(({id,...x})=>x),outputs:selected.outputs.map(({id,...x})=>x)})});setSelected(updated);toast.success("Módulo guardado.");await load()}catch(e){toast.error(e instanceof Error?e.message:"No fue posible guardar.")}finally{setSaving(false)}};
  const remove=async()=>{if(!selected||!confirm(`¿Eliminar ${selected.name}?`))return;await browserApiRequest(`/api/admin/generation-modules/${selected.id}`,{method:"DELETE"});setSelected(null);toast.success("Módulo eliminado.");await load()};
  return <div className="space-y-7">
    <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.28em] text-red-400">Pipeline central</p><h1 className="mt-2 text-3xl font-semibold text-white">Módulos de generación</h1><p className="mt-2 max-w-3xl text-sm text-zinc-500">Configura entradas, salidas y pasos Workflow/Python que podrán ejecutarse en Docker local, RunPod o modo simulado.</p></div><button onClick={()=>setShowCreate(true)} className="inline-flex h-11 items-center gap-2 rounded-xl bg-red-600 px-4 text-sm font-semibold text-white hover:bg-red-500"><Plus size={17}/>Nuevo módulo</button></header>
    <div className="grid gap-6 xl:grid-cols-[360px_minmax(0,1fr)]">
      <section className="luxia-panel overflow-hidden rounded-3xl"><div className="border-b border-white/6 p-4"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-zinc-700" size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar módulos..." className="h-10 w-full rounded-xl border border-white/7 bg-black/30 pl-10 pr-3 text-sm text-white outline-none focus:border-red-500/40"/></div></div><div className="max-h-[720px] overflow-y-auto p-3">{loading?<div className="flex justify-center p-10"><LoaderCircle className="animate-spin text-red-500"/></div>:items.length===0?<div className="p-8 text-center text-sm text-zinc-600">No hay módulos.</div>:items.map(m=><button key={m.id} onClick={()=>setSelected(m)} className={`mb-2 w-full rounded-2xl border p-4 text-left transition ${selected?.id===m.id?"border-red-500/35 bg-red-500/8":"border-white/6 bg-white/[.02] hover:border-white/12"}`}><div className="flex items-start justify-between gap-3"><div><p className="font-medium text-white">{m.name}</p><p className="mt-1 font-mono text-xs text-zinc-600">{m.key} · v{m.version}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-semibold uppercase ${m.is_active?"bg-emerald-500/10 text-emerald-400":"bg-zinc-800 text-zinc-500"}`}>{m.is_active?"Activo":"Inactivo"}</span></div><div className="mt-3 flex gap-3 text-xs text-zinc-600"><span>{m.inputs.length} entradas</span><span>{m.steps.length} pasos</span><span>{m.outputs.length} salidas</span></div></button>)}</div></section>
      {!selected?<section className="luxia-panel flex min-h-[520px] flex-col items-center justify-center rounded-3xl p-10 text-center"><Boxes size={44} className="text-zinc-800"/><h2 className="mt-5 text-xl font-semibold text-white">Selecciona un módulo</h2><p className="mt-2 max-w-md text-sm text-zinc-600">El editor mostrará aquí su contrato de entrada/salida y pipeline.</p></section>:<Editor module={selected} setModule={setSelected} onSave={save} onDelete={remove} saving={saving} onWorkflow={()=>setWorkflowModal(true)} onPython={()=>setPythonModal(true)}/>}    </div>
    {showCreate&&<CreateModal onClose={()=>setShowCreate(false)} onCreated={m=>{setItems(x=>[m,...x]);setSelected(m);setShowCreate(false)}}/>}
    {workflowModal&&selected&&<WorkflowModal module={selected} onClose={()=>setWorkflowModal(false)} onSaved={m=>{setSelected(m);setWorkflowModal(false);void load()}}/>}
    {pythonModal&&selected&&<PythonModal module={selected} onClose={()=>setPythonModal(false)} onSaved={m=>{setSelected(m);setPythonModal(false);void load()}}/>}
  </div>
}

function Editor({module,setModule,onSave,onDelete,saving,onWorkflow,onPython}:{module:GenerationModule;setModule:(m:GenerationModule)=>void;onSave:()=>void;onDelete:()=>void;saving:boolean;onWorkflow:()=>void;onPython:()=>void}){
 const patch=(v:Partial<GenerationModule>)=>setModule({...module,...v});
 const move=async(id:number,dir:-1|1)=>{const sorted=[...module.steps].sort((a,b)=>a.position-b.position);const i=sorted.findIndex(x=>x.id===id),j=i+dir;if(j<0||j>=sorted.length)return;[sorted[i],sorted[j]]=[sorted[j],sorted[i]];const items=sorted.map((x,position)=>({step_id:x.id,position}));const m=await browserApiRequest<GenerationModule>(`/api/admin/generation-modules/${module.id}/steps/reorder`,{method:"PUT",body:JSON.stringify({items})});setModule(m)};
 const delStep=async(id:number)=>{const m=await browserApiRequest<GenerationModule>(`/api/admin/generation-modules/${module.id}/steps/${id}`,{method:"DELETE"});setModule(m)};
 return <section className="luxia-panel overflow-hidden rounded-3xl"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/6 p-5"><div><h2 className="text-xl font-semibold text-white">{module.name}</h2><p className="mt-1 font-mono text-xs text-zinc-600">{module.key} · ID {module.id}</p></div><div className="flex gap-2"><button onClick={onDelete} className="h-10 rounded-xl border border-red-500/20 px-3 text-sm text-red-400 hover:bg-red-500/10"><Trash2 size={16}/></button><button onClick={onSave} disabled={saving} className="inline-flex h-10 items-center gap-2 rounded-xl bg-red-600 px-4 text-sm font-semibold text-white disabled:opacity-50">{saving?<LoaderCircle size={16} className="animate-spin"/>:<Save size={16}/>}Guardar</button></div></div>
 <div className="space-y-7 p-5"><div className="grid gap-4 md:grid-cols-2"><Field label="Nombre"><input value={module.name} onChange={e=>patch({name:e.target.value})} className="gm-input"/></Field><Field label="Categoría"><input value={module.category} onChange={e=>patch({category:e.target.value})} className="gm-input"/></Field><Field label="Motor predeterminado"><select value={module.default_execution_engine} onChange={e=>patch({default_execution_engine:e.target.value as GenerationExecutionEngine})} className="gm-input">{engines.map(e=><option key={e.value} value={e.value}>{e.label}</option>)}</select></Field><Field label="Estado"><select value={String(module.is_active)} onChange={e=>patch({is_active:e.target.value==="true"})} className="gm-input"><option value="true">Activo</option><option value="false">Inactivo</option></select></Field><Field label="Descripción" wide><textarea value={module.description??""} onChange={e=>patch({description:e.target.value})} className="gm-input min-h-24 py-3"/></Field></div>
 <Contract title="Entradas" onAdd={()=>patch({inputs:[...module.inputs,emptyInput(module.inputs.length)]})}>{module.inputs.map((x,i)=><ContractRow key={i}><input value={x.key} onChange={e=>patch({inputs:module.inputs.map((v,j)=>j===i?{...v,key:e.target.value}:v)})} className="gm-input" placeholder="clave"/><input value={x.name} onChange={e=>patch({inputs:module.inputs.map((v,j)=>j===i?{...v,name:e.target.value}:v)})} className="gm-input" placeholder="nombre"/><select value={x.input_type} onChange={e=>patch({inputs:module.inputs.map((v,j)=>j===i?{...v,input_type:e.target.value as any}:v)})} className="gm-input">{inputTypes.map(t=><option key={t}>{t}</option>)}</select><button onClick={()=>patch({inputs:module.inputs.filter((_,j)=>j!==i).map((v,position)=>({...v,position}))})} className="gm-delete"><X size={16}/></button></ContractRow>)}</Contract>
 <Contract title="Pipeline" actions={<><button onClick={onWorkflow} className="gm-secondary"><FileJson2 size={16}/>Workflow</button><button onClick={onPython} className="gm-secondary"><Code2 size={16}/>Python</button></>}>{module.steps.length===0?<p className="py-8 text-center text-sm text-zinc-600">Agrega el primer paso.</p>:module.steps.slice().sort((a,b)=>a.position-b.position).map((s,i)=><div key={s.id} className="flex items-center gap-3 rounded-2xl border border-white/6 bg-black/20 p-4"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-red-500/10 text-red-400">{s.step_type==="workflow"?<FileJson2 size={18}/>:<Code2 size={18}/>}</div><div className="min-w-0 flex-1"><p className="font-medium text-white">{i+1}. {s.name}</p><p className="font-mono text-xs text-zinc-600">{s.key} · {s.step_type}</p></div><button onClick={()=>void move(s.id,-1)} className="gm-icon"><ChevronUp size={15}/></button><button onClick={()=>void move(s.id,1)} className="gm-icon"><ChevronDown size={15}/></button><button onClick={()=>void delStep(s.id)} className="gm-delete"><Trash2 size={15}/></button></div>)}</Contract>
 <Contract title="Salidas" onAdd={()=>patch({outputs:[...module.outputs,emptyOutput(module.outputs.length)]})}>{module.outputs.map((x,i)=><ContractRow key={i}><input value={x.key} onChange={e=>patch({outputs:module.outputs.map((v,j)=>j===i?{...v,key:e.target.value}:v)})} className="gm-input" placeholder="clave"/><input value={x.name} onChange={e=>patch({outputs:module.outputs.map((v,j)=>j===i?{...v,name:e.target.value}:v)})} className="gm-input" placeholder="nombre"/><select value={x.output_type} onChange={e=>patch({outputs:module.outputs.map((v,j)=>j===i?{...v,output_type:e.target.value as any}:v)})} className="gm-input">{outputTypes.map(t=><option key={t}>{t}</option>)}</select><button onClick={()=>patch({outputs:module.outputs.filter((_,j)=>j!==i).map((v,position)=>({...v,position}))})} className="gm-delete"><X size={16}/></button></ContractRow>)}</Contract><TestConsole module={module}/></div></section>
}
function Field({label,wide,children}:{label:string;wide?:boolean;children:React.ReactNode}){return <label className={wide?"md:col-span-2":""}><span className="mb-2 block text-xs font-semibold uppercase tracking-wider text-zinc-600">{label}</span>{children}</label>}
function Contract({title,onAdd,actions,children}:{title:string;onAdd?:()=>void;actions?:React.ReactNode;children:React.ReactNode}){return <div><div className="mb-3 flex items-center justify-between"><h3 className="text-sm font-semibold uppercase tracking-[.18em] text-zinc-400">{title}</h3><div className="flex gap-2">{actions}{onAdd&&<button onClick={onAdd} className="gm-secondary"><Plus size={15}/>Agregar</button>}</div></div><div className="space-y-2 rounded-2xl border border-white/6 bg-white/[.015] p-3">{children}</div></div>}
function ContractRow({children}:{children:React.ReactNode}){return <div className="grid gap-2 md:grid-cols-[1fr_1.4fr_.8fr_auto]">{children}</div>}

function ModalShell({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4 backdrop-blur-sm"><div className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-3xl border border-white/10 bg-[#0b0b0d] shadow-2xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b border-white/7 bg-[#0b0b0d]/95 p-5"><h2 className="text-xl font-semibold text-white">{title}</h2><button onClick={onClose} className="gm-icon"><X size={18}/></button></div><div className="p-5">{children}</div></div></div>}
function CreateModal({onClose,onCreated}:{onClose:()=>void;onCreated:(m:GenerationModule)=>void}){const [f,setF]=useState({key:"",name:"",description:"",category:"tryon",default_execution_engine:"simulated" as GenerationExecutionEngine});const [busy,setBusy]=useState(false);return <ModalShell title="Nuevo módulo" onClose={onClose}><div className="grid gap-4 md:grid-cols-2"><Field label="Clave"><input className="gm-input" value={f.key} onChange={e=>setF({...f,key:e.target.value.toLowerCase().replace(/[^a-z0-9._-]/g,"-")})}/></Field><Field label="Nombre"><input className="gm-input" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></Field><Field label="Categoría"><input className="gm-input" value={f.category} onChange={e=>setF({...f,category:e.target.value})}/></Field><Field label="Motor"><select className="gm-input" value={f.default_execution_engine} onChange={e=>setF({...f,default_execution_engine:e.target.value as GenerationExecutionEngine})}>{engines.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></Field><Field label="Descripción" wide><textarea className="gm-input min-h-24 py-3" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></Field></div><button disabled={busy||f.key.length<2||f.name.length<2} onClick={async()=>{setBusy(true);try{onCreated(await browserApiRequest<GenerationModule>("/api/admin/generation-modules",{method:"POST",body:JSON.stringify({...f,version:1,is_active:true,metadata:{},inputs:[],outputs:[],steps:[]})}))}finally{setBusy(false)}}} className="mt-5 h-11 w-full rounded-xl bg-red-600 font-semibold text-white disabled:opacity-40">Crear módulo</button></ModalShell>}
function WorkflowModal({module,onClose,onSaved}:{module:GenerationModule;onClose:()=>void;onSaved:(m:GenerationModule)=>void}){const [key,setKey]=useState(`workflow_${module.steps.length+1}`),[name,setName]=useState("Workflow ComfyUI"),[json,setJson]=useState(""),[inputs,setInputs]=useState<WorkflowInputBinding[]>([]),[outputs,setOutputs]=useState<WorkflowOutputBinding[]>([]);const parsed=useMemo(()=>{try{return JSON.parse(json)}catch{return null}},[json]);return <ModalShell title="Importar workflow" onClose={onClose}><div className="grid gap-3 md:grid-cols-2"><input className="gm-input" value={key} onChange={e=>setKey(e.target.value)} placeholder="clave"/><input className="gm-input" value={name} onChange={e=>setName(e.target.value)} placeholder="nombre"/></div><textarea className="gm-input mt-3 min-h-56 py-3 font-mono text-xs" value={json} onChange={e=>setJson(e.target.value)} placeholder="Pega aquí el JSON API de ComfyUI"/><BindingEditor title="Entradas del workflow" rows={inputs} add={()=>setInputs([...inputs,{module_input_key:module.inputs[0]?.key??"",node_id:"",input_field:"image"}])} render={(x,i)=><ContractRow key={i}><select className="gm-input" value={x.module_input_key} onChange={e=>setInputs(inputs.map((v,j)=>j===i?{...v,module_input_key:e.target.value}:v))}>{module.inputs.map(v=><option key={v.key}>{v.key}</option>)}</select><input className="gm-input" value={x.node_id} onChange={e=>setInputs(inputs.map((v,j)=>j===i?{...v,node_id:e.target.value}:v))} placeholder="node_id"/><input className="gm-input" value={x.input_field} onChange={e=>setInputs(inputs.map((v,j)=>j===i?{...v,input_field:e.target.value}:v))} placeholder="campo"/><button className="gm-delete" onClick={()=>setInputs(inputs.filter((_,j)=>j!==i))}><X size={15}/></button></ContractRow>}/><BindingEditor title="Salidas del workflow" rows={outputs} add={()=>setOutputs([...outputs,{module_output_key:module.outputs[0]?.key??"",node_id:""}])} render={(x,i)=><ContractRow key={i}><select className="gm-input" value={x.module_output_key} onChange={e=>setOutputs(outputs.map((v,j)=>j===i?{...v,module_output_key:e.target.value}:v))}>{module.outputs.map(v=><option key={v.key}>{v.key}</option>)}</select><input className="gm-input md:col-span-2" value={x.node_id} onChange={e=>setOutputs(outputs.map((v,j)=>j===i?{...v,node_id:e.target.value}:v))} placeholder="node_id de salida"/><button className="gm-delete" onClick={()=>setOutputs(outputs.filter((_,j)=>j!==i))}><X size={15}/></button></ContractRow>}/><button disabled={!parsed} onClick={async()=>onSaved(await browserApiRequest<GenerationModule>(`/api/admin/generation-modules/${module.id}/steps/workflow`,{method:"POST",body:JSON.stringify({key,name,position:module.steps.length,workflow_json:parsed,input_bindings:inputs,output_bindings:outputs,is_enabled:true})}))} className="mt-5 h-11 w-full rounded-xl bg-red-600 font-semibold text-white disabled:opacity-40">Importar workflow</button></ModalShell>}
function BindingEditor<T>({title,rows,add,render}:{title:string;rows:T[];add:()=>void;render:(x:T,i:number)=>React.ReactNode}){return <div className="mt-5"><div className="mb-2 flex items-center justify-between"><p className="text-xs font-semibold uppercase tracking-wider text-zinc-500">{title}</p><button onClick={add} className="gm-secondary"><Plus size={14}/>Agregar</button></div><div className="space-y-2">{rows.map(render)}</div></div>}
function PythonModal({module,onClose,onSaved}:{module:GenerationModule;onClose:()=>void;onSaved:(m:GenerationModule)=>void}){const [key,setKey]=useState(`python_${module.steps.length+1}`),[name,setName]=useState("Paso Python"),[entrypoint,setEntrypoint]=useState("run"),[source,setSource]=useState("def run(inputs):\n    return inputs\n");return <ModalShell title="Nuevo paso Python" onClose={onClose}><div className="grid gap-3 md:grid-cols-3"><input className="gm-input" value={key} onChange={e=>setKey(e.target.value)} placeholder="clave"/><input className="gm-input" value={name} onChange={e=>setName(e.target.value)} placeholder="nombre"/><input className="gm-input" value={entrypoint} onChange={e=>setEntrypoint(e.target.value)} placeholder="función"/></div><textarea className="gm-input mt-3 min-h-80 py-3 font-mono text-xs" value={source} onChange={e=>setSource(e.target.value)}/><button onClick={async()=>onSaved(await browserApiRequest<GenerationModule>(`/api/admin/generation-modules/${module.id}/steps/python`,{method:"POST",body:JSON.stringify({key,name,position:module.steps.length,source_code:source,entrypoint,timeout_seconds:300,input_mapping:{},output_mapping:{},is_enabled:true})}))} className="mt-5 h-11 w-full rounded-xl bg-red-600 font-semibold text-white">Agregar paso Python</button></ModalShell>}


function TestConsole({module}:{module:GenerationModule}){
 const initialInputs=useMemo(()=>Object.fromEntries(module.inputs.map(input=>[input.key,input.default_value??(input.input_type==="boolean"?false:"")])),[module.id,module.inputs]);
 const [inputsJson,setInputsJson]=useState(()=>JSON.stringify(initialInputs,null,2));
 const [execution,setExecution]=useState<GenerationModuleExecution|null>(null);
 const [busy,setBusy]=useState(false);
 const [runtimeHealth,setRuntimeHealth]=useState<GenerationRuntimeHealth|null>(null);
 const [healthBusy,setHealthBusy]=useState(false);
 const checkHealth=async()=>{setHealthBusy(true);try{setRuntimeHealth(await browserApiRequest<GenerationRuntimeHealth>("/api/admin/generation-modules/runtime/health"))}catch(e){toast.error(e instanceof Error?e.message:"No fue posible consultar los runtimes.")}finally{setHealthBusy(false)}};
 useEffect(()=>{setInputsJson(JSON.stringify(initialInputs,null,2));setExecution(null);void checkHealth()},[module.id,initialInputs]);
 useEffect(()=>{if(!execution||!["queued","running"].includes(execution.status))return;const timer=setInterval(async()=>{try{const next=await browserApiRequest<GenerationModuleExecution>(`/api/admin/generation-modules/executions/${execution.id}`);setExecution(next)}catch{}},900);return()=>clearInterval(timer)},[execution?.id,execution?.status]);
 const run=async()=>{let inputs:Record<string,unknown>;try{inputs=JSON.parse(inputsJson)}catch{toast.error("El JSON de entradas no es válido.");return}setBusy(true);try{const result=await browserApiRequest<GenerationModuleExecution>(`/api/admin/generation-modules/${module.id}/executions`,{method:"POST",body:JSON.stringify({inputs,engine:module.default_execution_engine})});setExecution(result);toast.success("Prueba iniciada.")}catch(e){toast.error(e instanceof Error?e.message:"No fue posible iniciar la prueba.")}finally{setBusy(false)}};
 const refresh=async()=>{if(!execution)return;setExecution(await browserApiRequest<GenerationModuleExecution>(`/api/admin/generation-modules/executions/${execution.id}`))};
 const cancel=async()=>{if(!execution)return;setExecution(await browserApiRequest<GenerationModuleExecution>(`/api/admin/generation-modules/executions/${execution.id}/cancel`,{method:"POST"}))};
 return <div><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-sm font-semibold uppercase tracking-[.18em] text-zinc-400">Consola de prueba</h3><p className="mt-1 text-xs text-zinc-600">Ejecuta el pipeline y revisa contexto, tiempos, logs y salidas.</p></div><div className="flex gap-2"><button onClick={()=>void checkHealth()} disabled={healthBusy} className="gm-secondary"><RefreshCw size={15} className={healthBusy?"animate-spin":""}/>Runtimes</button>{execution&&<button onClick={()=>void refresh()} className="gm-secondary"><RefreshCw size={15}/>Actualizar</button>}{execution&&["queued","running"].includes(execution.status)&&<button onClick={()=>void cancel()} className="gm-secondary"><Square size={14}/>Cancelar</button>}<button disabled={busy||module.steps.length===0} onClick={()=>void run()} className="inline-flex h-9 items-center gap-2 rounded-xl bg-red-600 px-4 text-xs font-semibold text-white disabled:opacity-40">{busy?<LoaderCircle size={15} className="animate-spin"/>:<Play size={15}/>}Ejecutar prueba</button></div></div>
 {runtimeHealth&&<div className="mb-4 grid gap-3 md:grid-cols-3">{(["simulated","local_docker","runpod_serverless"] as const).map(key=>{const health=runtimeHealth[key];return <div key={key} className="rounded-2xl border border-white/6 bg-black/20 p-3"><div className="flex items-center justify-between"><span className="font-mono text-xs text-zinc-400">{key}</span><span className={`rounded-full px-2 py-1 text-[10px] font-semibold uppercase ${health.available?"bg-emerald-500/10 text-emerald-400":"bg-red-500/10 text-red-400"}`}>{health.available?"Disponible":"Sin conexión"}</span></div>{health.error&&<p className="mt-2 line-clamp-2 text-[11px] text-red-300">{health.error}</p>}</div>})}</div>}
 <div className="grid gap-4 xl:grid-cols-2"><div className="rounded-2xl border border-white/6 bg-black/20 p-4"><p className="mb-2 text-xs font-semibold uppercase tracking-wider text-zinc-500">Entradas JSON</p><textarea value={inputsJson} onChange={e=>setInputsJson(e.target.value)} className="gm-input min-h-64 py-3 font-mono text-xs"/></div><div className="rounded-2xl border border-white/6 bg-black/20 p-4">{!execution?<div className="flex min-h-64 items-center justify-center text-sm text-zinc-600">Aún no hay ejecución.</div>:<div className="space-y-4"><div className="flex items-center justify-between"><span className={`rounded-full px-3 py-1 text-xs font-semibold uppercase ${execution.status==="completed"?"bg-emerald-500/10 text-emerald-400":execution.status==="failed"?"bg-red-500/10 text-red-400":"bg-amber-500/10 text-amber-300"}`}>{execution.status}</span><span className="text-xs text-zinc-500">{execution.duration_ms??0} ms</span></div><div className="h-2 overflow-hidden rounded-full bg-white/5"><div className="h-full bg-red-600 transition-all" style={{width:`${execution.progress}%`}}/></div><div className="space-y-2">{execution.steps.map(step=><div key={step.step_key} className="flex items-center justify-between rounded-xl border border-white/5 p-3"><div><p className="text-sm text-white">{step.step_name}</p><p className="font-mono text-[11px] text-zinc-600">{step.step_key} · {step.step_type}</p></div><div className="text-right"><p className="text-xs uppercase text-zinc-400">{step.status}</p><p className="text-[11px] text-zinc-600">{step.duration_ms??0} ms</p></div></div>)}</div>{execution.error&&<p className="rounded-xl border border-red-500/20 bg-red-500/5 p-3 text-xs text-red-300">{execution.error}</p>}</div>}</div></div>
 {execution&&<div className="mt-4 grid gap-4 xl:grid-cols-3"><JsonPanel title="Contexto" value={execution.context}/><JsonPanel title="Salidas" value={execution.outputs}/><div className="rounded-2xl border border-white/6 bg-black/20 p-4"><p className="mb-3 text-xs font-semibold uppercase tracking-wider text-zinc-500">Logs</p><div className="max-h-72 space-y-2 overflow-y-auto">{execution.logs.map((log,index)=><div key={`${log.timestamp}-${index}`} className="rounded-xl border border-white/5 p-3 text-xs"><p className={log.level==="error"?"text-red-300":log.level==="warning"?"text-amber-300":"text-zinc-300"}>{log.message}</p><p className="mt-1 font-mono text-[10px] text-zinc-700">{log.step_key??"pipeline"} · {new Date(log.timestamp).toLocaleTimeString()}</p></div>)}</div></div></div>}
 </div>
}
function JsonPanel({title,value}:{title:string;value:unknown}){return <div className="rounded-2xl border border-white/6 bg-black/20 p-4"><p className="mb-3 text-xs font-semibold uppercase tracking-wider text-zinc-500">{title}</p><pre className="max-h-72 overflow-auto whitespace-pre-wrap break-all font-mono text-[11px] leading-5 text-zinc-400">{JSON.stringify(value,null,2)}</pre></div>}
