"use client";
import { DollarSign, LoaderCircle, Save, Trash2 } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { browserApiRequest } from "@/lib/api/browser-api";
import type { ProviderGpuPriceResponse } from "@/types/admin-pricing-coupons";
export function ProviderGpuPricingTable({ provider, gpuKeys }: { provider: string; gpuKeys: readonly string[] }) {
  const [items, setItems] = useState<ProviderGpuPriceResponse[]>([]); const [values, setValues] = useState<Record<string,string>>({}); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null);
  const unique=useMemo(()=>[...new Set(gpuKeys.filter(Boolean))],[gpuKeys]);
  const load=useCallback(async()=>{setLoading(true);try{const response=await browserApiRequest<ProviderGpuPriceResponse[]>(`/api/admin/provider-gpu-prices?provider=${encodeURIComponent(provider)}`);setItems(response);setValues(Object.fromEntries(response.map(item=>[item.gpu_key,String(item.cost_usd_per_second)])));}catch(cause){toast.error(cause instanceof Error?cause.message:"No fue posible cargar los costos GPU.");}finally{setLoading(false);}},[provider]);
  useEffect(()=>{void load();},[load]);
  async function save(gpuKey:string){const cost=Number(values[gpuKey]??0);if(!Number.isFinite(cost)||cost<0){toast.error("El costo debe ser un número no negativo.");return;}setBusy(gpuKey);try{const saved=await browserApiRequest<ProviderGpuPriceResponse>("/api/admin/provider-gpu-prices",{method:"PUT",body:JSON.stringify({provider,gpu_key:gpuKey,cost_usd_per_second:cost,is_active:true})});setItems(current=>current.some(item=>item.gpu_key===gpuKey)?current.map(item=>item.gpu_key===gpuKey?saved:item):[...current,saved]);toast.success(`Costo de ${gpuKey} guardado.`);}catch(cause){toast.error(cause instanceof Error?cause.message:"No fue posible guardar el costo.");}finally{setBusy(null);}}
  async function remove(gpuKey:string){const item=items.find(current=>current.gpu_key===gpuKey);if(!item)return;setBusy(gpuKey);try{await browserApiRequest(`/api/admin/provider-gpu-prices/${item.id}`,{method:"DELETE"});setItems(current=>current.filter(current=>current.id!==item.id));setValues(current=>({...current,[gpuKey]:""}));toast.success("Costo eliminado.");}catch(cause){toast.error(cause instanceof Error?cause.message:"No fue posible eliminar el costo.");}finally{setBusy(null);}}
  return <div className="mt-7 border-t border-white/6 pt-6"><div className="flex items-center gap-2"><DollarSign size={17} className="text-red-400"/><h3 className="text-sm font-semibold text-white">Costo por GPU</h3></div><p className="mt-2 text-xs leading-5 text-zinc-600">Precio manual en USD por segundo. Se usa para estimaciones y cobros.</p>{loading?<div className="flex h-28 items-center justify-center"><LoaderCircle className="animate-spin text-red-500"/></div>:<div className="mt-4 overflow-x-auto rounded-2xl border border-white/6"><table className="w-full min-w-[620px] text-left text-xs"><thead className="bg-black/25 uppercase tracking-wider text-zinc-600"><tr><th className="p-3">GPU</th><th>Costo USD/segundo</th><th>Estado</th><th className="pr-3 text-right">Acciones</th></tr></thead><tbody>{unique.map(gpu=>{const existing=items.find(item=>item.gpu_key===gpu);const isBusy=busy===gpu;return <tr key={gpu} className="border-t border-white/5"><td className="p-3 font-medium text-white">{gpu}</td><td className="py-2"><input type="number" min="0" step="0.000001" value={values[gpu]??""} onChange={event=>setValues(current=>({...current,[gpu]:event.target.value}))} placeholder="0.000000" className="h-10 w-48 rounded-xl border border-white/8 bg-black/30 px-3 text-white"/></td><td className="text-zinc-500">{existing?"Configurado":"Pendiente"}</td><td className="pr-3 text-right"><button disabled={isBusy} onClick={()=>void save(gpu)} className="mr-2 inline-flex size-9 items-center justify-center rounded-lg bg-red-600 text-white disabled:opacity-50">{isBusy?<LoaderCircle size={14} className="animate-spin"/>:<Save size={14}/>}</button>{existing&&<button disabled={isBusy} onClick={()=>void remove(gpu)} className="inline-flex size-9 items-center justify-center rounded-lg border border-white/8 text-zinc-500 hover:text-red-300 disabled:opacity-50"><Trash2 size={14}/></button>}</td></tr>})}</tbody></table></div>}</div>;
}
