"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Coins, LoaderCircle, RefreshCcw, Search, TriangleAlert } from "lucide-react";
import { browserApiRequest } from "@/lib/api/browser-api";

interface TokenTransaction { id:number; user_id:number; transaction_type:string; amount:number; balance_after:number; source:string|null; reference_id:string|null; description:string|null; created_at:string; }

export default function TokenMovementsPage() {
  const [items,setItems]=useState<TokenTransaction[]>([]); const [userId,setUserId]=useState(""); const [kind,setKind]=useState(""); const [search,setSearch]=useState(""); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
  const load=useCallback(async()=>{ setLoading(true); setError(null); try { const q=new URLSearchParams({skip:"0",limit:"200"}); if(userId.trim()) q.set("user_id",userId.trim()); if(kind) q.set("transaction_type",kind); setItems(await browserApiRequest<TokenTransaction[]>(`/api/admin/token-transactions?${q}`)); } catch(e){ setError(e instanceof Error?e.message:"No fue posible cargar los movimientos de tokens."); } finally { setLoading(false); } },[userId,kind]);
  useEffect(()=>{void load()},[load]);
  const visible=useMemo(()=>{const q=search.trim().toLowerCase(); return q?items.filter(x=>[x.id,x.user_id,x.transaction_type,x.source??"",x.reference_id??"",x.description??""].some(v=>String(v).toLowerCase().includes(q))):items},[items,search]);
  return <div>
    <section className="luxia-panel overflow-hidden rounded-3xl"><div className="border-b border-white/6 p-6"><div className="flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between"><div className="flex items-start gap-4"><div className="luxia-red-glow flex size-14 shrink-0 items-center justify-center rounded-2xl border border-red-500/20 bg-red-950/25 text-red-400"><Coins size={24}/></div><div><p className="text-[10px] font-semibold tracking-[0.2em] text-red-500 uppercase">Comercial</p><h1 className="mt-2 text-2xl font-semibold text-white">Movimientos de tokens</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-zinc-600">Historial de créditos, consumos, ajustes y devoluciones de tokens. Las conciliaciones y reembolsos monetarios se administran desde Pagos.</p></div></div><button onClick={()=>void load()} disabled={loading} className="inline-flex h-11 items-center gap-2 rounded-xl border border-white/8 px-4 text-sm text-zinc-400 disabled:opacity-50"><RefreshCcw size={16} className={loading?"animate-spin":undefined}/>Actualizar</button></div></div></section>
    <section className="luxia-panel mt-5 rounded-3xl p-5"><div className="grid gap-4 md:grid-cols-3"><label className="relative"><Search size={16} className="pointer-events-none absolute top-1/2 left-4 -translate-y-1/2 text-zinc-700"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar movimiento..." className="h-11 w-full rounded-xl border border-white/8 bg-black/30 pr-4 pl-11 text-sm text-white"/></label><input type="number" min={1} value={userId} onChange={e=>setUserId(e.target.value)} placeholder="User ID" className="h-11 rounded-xl border border-white/8 bg-black/30 px-4 text-sm text-white"/><select value={kind} onChange={e=>setKind(e.target.value)} className="h-11 rounded-xl border border-white/8 bg-[#09090a] px-4 text-sm text-zinc-300"><option value="">Créditos y débitos</option><option value="credit">Créditos</option><option value="debit">Débitos</option></select></div></section>
    {loading&&<section className="luxia-panel mt-5 flex min-h-80 items-center justify-center rounded-3xl"><LoaderCircle className="animate-spin text-red-500"/></section>}
    {!loading&&error&&<section className="luxia-panel mt-5 rounded-3xl p-6"><div className="flex gap-3 rounded-2xl border border-red-500/15 bg-red-950/15 p-5"><TriangleAlert size={19} className="text-red-400"/><p className="text-sm text-red-300">{error}</p></div></section>}
    {!loading&&!error&&<section className="luxia-panel mt-5 overflow-hidden rounded-3xl">{visible.length===0?<div className="p-12 text-center text-sm text-zinc-600">No existen movimientos que coincidan.</div>:<div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left"><thead className="border-b border-white/6 bg-black/20 text-[10px] tracking-[.14em] text-zinc-700 uppercase"><tr><th className="px-5 py-4">Movimiento</th><th className="px-5 py-4">Usuario</th><th className="px-5 py-4">Tipo</th><th className="px-5 py-4">Cantidad</th><th className="px-5 py-4">Saldo posterior</th><th className="px-5 py-4">Origen</th><th className="px-5 py-4">Fecha</th></tr></thead><tbody className="divide-y divide-white/5">{visible.map(x=><tr key={x.id} className="hover:bg-white/[.02]"><td className="px-5 py-4"><p className="text-sm font-medium text-white">#{x.id}</p><p className="mt-1 max-w-md truncate text-xs text-zinc-600">{x.description??"Sin descripción"}</p></td><td className="px-5 py-4 text-sm text-zinc-400">#{x.user_id}</td><td className="px-5 py-4"><span className={`rounded-full border px-2.5 py-1 text-[10px] font-semibold ${x.amount>=0?"border-emerald-500/20 bg-emerald-950/15 text-emerald-400":"border-amber-500/20 bg-amber-950/15 text-amber-400"}`}>{x.transaction_type}</span></td><td className={`px-5 py-4 text-sm font-semibold ${x.amount>=0?"text-emerald-400":"text-amber-400"}`}>{x.amount>0?"+":""}{x.amount.toLocaleString("es-MX")}</td><td className="px-5 py-4 text-sm text-white">{x.balance_after.toLocaleString("es-MX")}</td><td className="px-5 py-4"><p className="text-xs text-zinc-400">{x.source??"—"}</p><p className="mt-1 font-mono text-[10px] text-zinc-700">{x.reference_id??""}</p></td><td className="px-5 py-4 text-xs text-zinc-500">{new Date(x.created_at).toLocaleString("es-MX")}</td></tr>)}</tbody></table></div>}</section>}
  </div>
}
