"use client";
import {AlertTriangle, LoaderCircle, RefreshCcw, X} from "lucide-react";
import {useEffect,useState} from "react";
import {toast} from "sonner";
import {browserApiRequest} from "@/lib/api/browser-api";
import type {BillingPaymentHistoryResponse,BillingPaymentReconcileResponse} from "@/types/admin-billing-payments";
interface Props{paymentId:number;onClose:()=>void;onUpdated:(payment:BillingPaymentHistoryResponse)=>void}
const date=(v:string|null)=>!v?"No disponible":new Date(v).toLocaleString("es-MX");
const money=(v:string,c:string)=>new Intl.NumberFormat("es-MX",{style:"currency",currency:c.toUpperCase()}).format(Number(v)||0);
const statusLabel=(p:BillingPaymentHistoryResponse)=>p.is_payment_attempt?"Intento de checkout":({processing:"Pago en proceso",succeeded:"Pagado",failed:"Fallido",canceled:"Cancelado",refunded:"Reembolsado",partially_refunded:"Reembolso parcial",pending:"Pendiente de confirmar"}[p.display_status]||p.display_status);
function Info({label,value}:{label:string;value:unknown}){return <article className="rounded-2xl border border-white/7 bg-black/20 p-4"><p className="text-xs text-zinc-600">{label}</p><p className="mt-2 break-words text-sm font-semibold text-white">{value===null||value===""?"No aplica":String(value)}</p></article>}
export function BillingPaymentDialog({paymentId,onClose,onUpdated}:Props){
 const [payment,setPayment]=useState<BillingPaymentHistoryResponse|null>(null);const[loading,setLoading]=useState(true);const[action,setAction]=useState(false);
 useEffect(()=>{let cancelled=false;(async()=>{try{const r=await browserApiRequest<BillingPaymentHistoryResponse>(`/api/admin/billing-payments/${paymentId}`);if(!cancelled)setPayment(r)}catch(e){toast.error(e instanceof Error?e.message:"No fue posible cargar el pago.")}finally{if(!cancelled)setLoading(false)}})();return()=>{cancelled=true}},[paymentId]);
 async function reconcile(){if(!payment?.can_reconcile)return;setAction(true);try{const r=await browserApiRequest<BillingPaymentReconcileResponse>(`/api/admin/billing-payments/${payment.id}/reconcile`,{method:"POST"});setPayment(r.payment);onUpdated(r.payment);toast.success(r.message)}catch(e){toast.error(e instanceof Error?e.message:"No fue posible conciliar.")}finally{setAction(false)}}
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4 backdrop-blur-sm" role="dialog"><article className="luxia-panel max-h-[94vh] w-full max-w-6xl overflow-auto rounded-3xl"><header className="sticky top-0 z-10 flex justify-between border-b border-white/6 bg-[#09090a]/95 p-6"><div><p className="text-[10px] font-semibold tracking-[.2em] text-red-500 uppercase">{payment?.is_payment_attempt?"Intento":"Pago"} #{paymentId}</p><h2 className="mt-2 text-xl font-semibold text-white">Detalle comercial</h2></div><button onClick={onClose} className="size-10 rounded-xl border border-white/8"><X className="m-auto text-zinc-500" size={17}/></button></header><div className="p-6">{loading&&<div className="flex min-h-64 items-center justify-center"><LoaderCircle className="animate-spin text-red-500"/></div>}{!loading&&payment&&<>
 <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Info label="Usuario" value={`#${payment.user_id}`}/><Info label="Qué ocurrió" value={statusLabel(payment)}/><Info label="Precio antes del descuento" value={money(payment.original_amount,payment.currency)}/><Info label="Cliente pagó" value={money(payment.final_amount,payment.currency)}/></section>
 <section className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Info label="Descuento aplicado" value={Number(payment.discount_amount)>0?money(payment.discount_amount,payment.currency):"Sin descuento"}/><Info label="Tipo de beneficio" value={payment.discount_source||"No aplica"}/><Info label="Cupón" value={payment.discount_code||"No se utilizó"}/><Info label="Porcentaje" value={payment.discount_percent?`${Number(payment.discount_percent).toFixed(2)} %`:"No aplica"}/></section>
 <section className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Info label="Origen comercial" value={payment.commercial_origin||payment.payment_type}/><Info label="PaymentIntent" value={payment.provider_payment_intent_id||(payment.provider_checkout_session_id?"Todavía no sincronizado desde Checkout":"No aplica")}/><Info label="Checkout Session" value={payment.provider_checkout_session_id}/><Info label="Charge" value={payment.provider_charge_id}/><Info label="Creado" value={date(payment.created_at)}/><Info label="Pagado" value={date(payment.paid_at)}/></section>
 {payment.failure_message&&<section className="mt-5 flex gap-3 rounded-2xl border border-red-500/15 bg-red-950/10 p-5"><AlertTriangle className="text-red-400" size={18}/><div><p className="font-semibold text-red-300">{payment.failure_code||"Pago fallido"}</p><p className="mt-2 text-xs text-red-300/75">{payment.failure_message}</p></div></section>}
 <section className="mt-5 rounded-2xl border border-blue-500/10 bg-blue-950/10 p-5"><h3 className="font-semibold text-blue-300">Conciliar con Stripe</h3><p className="mt-2 text-xs leading-6 text-blue-300/70">También funciona cuando falta el webhook: si existe un Checkout Session, consultaremos Stripe para saber si fue pagado. Si Stripe confirma el pago, se actualizarán la compra, los tokens y la bolsa automáticamente.</p><button onClick={()=>void reconcile()} disabled={action||!payment.can_reconcile} className="mt-4 inline-flex h-10 items-center gap-2 rounded-xl border border-blue-500/15 px-4 text-sm text-blue-300 disabled:opacity-40">{action?<LoaderCircle className="animate-spin" size={15}/>:<RefreshCcw size={15}/>}Conciliar</button><p className="mt-4 text-xs leading-6 text-zinc-500"><b className="text-zinc-300">Reembolsos:</b> se administran desde <b className="text-white">Caja y Bolsas</b>, donde también se actualizan los tokens, la reserva para IA y la caja financiera.</p></section>
 <details className="mt-5 rounded-2xl border border-white/7 bg-black/20 p-5"><summary className="cursor-pointer text-sm font-semibold text-white">Ver información técnica</summary><pre className="mt-4 max-h-72 overflow-auto rounded-xl bg-[#050506] p-4 text-xs text-zinc-400">{JSON.stringify(payment.metadata,null,2)}</pre></details>
 </>}</div></article></div>
}