"use client";

import { useCallback, useEffect, useState } from "react";
import { browserApiRequest } from "@/lib/api/browser-api";

type Module = { id:number; key:string; name:string; version:number; is_active:boolean; updated_at:string };
type Execution = { id:string; module_key:string; engine:string; status:string; progress:number; created_at:string; error?:string|null };

export default function GenerationOperationsPage(){
 const [modules,setModules]=useState<Module[]>([]),[executions,setExecutions]=useState<Execution[]>([]),[selected,setSelected]=useState<number|null>(null),[message,setMessage]=useState("");
 const load=useCallback(async()=>{const [m,e]=await Promise.all([browserApiRequest<{items:Module[]}>("/api/admin/generation-modules?limit=500"),browserApiRequest<{items:Execution[]}>("/api/admin/generation-modules/execution-history?limit=200")]);setModules(m.items);setExecutions(e.items)},[]);
 useEffect(()=>{void load()},[load]);
 const clone=async()=>{if(!selected)return;await browserApiRequest(`/api/admin/generation-modules/${selected}/clone`,{method:"POST",body:JSON.stringify({activate:false})});setMessage("Se creó una nueva versión en borrador.");await load()};
 const publish=async()=>{if(!selected)return;await browserApiRequest(`/api/admin/generation-modules/${selected}/publish`,{method:"POST",body:JSON.stringify({deactivate_other_versions:true})});setMessage("Versión publicada y versiones anteriores desactivadas.");await load()};
 const download=async()=>{if(!selected)return;const data=await browserApiRequest(`/api/admin/generation-modules/${selected}/export`);const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`generation-module-${selected}.json`;a.click();URL.revokeObjectURL(url)};
 return <div className="space-y-7"><header><p className="text-xs font-semibold uppercase tracking-[.28em] text-red-400">Operaciones</p><h1 className="mt-2 text-3xl font-semibold text-white">Jobs y versiones</h1><p className="mt-2 text-sm text-zinc-500">Publica versiones, clona borradores, exporta módulos y monitorea ejecuciones.</p></header>{message&&<div className="rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-4 text-sm text-emerald-300">{message}</div>}<section className="luxia-panel rounded-3xl p-5"><div className="flex flex-col gap-3 lg:flex-row"><select value={selected??""} onChange={e=>setSelected(e.target.value?Number(e.target.value):null)} className="h-11 flex-1 rounded-xl border border-white/10 bg-black/40 px-4 text-sm text-white"><option value="">Selecciona un módulo</option>{modules.map(m=><option key={m.id} value={m.id}>{m.name} · {m.key} · v{m.version} {m.is_active?"(publicado)":"(borrador)"}</option>)}</select><button onClick={()=>void clone()} className="rounded-xl border border-white/10 px-4 text-sm text-white">Clonar versión</button><button onClick={()=>void publish()} className="rounded-xl bg-red-600 px-4 text-sm font-semibold text-white">Publicar</button><button onClick={()=>void download()} className="rounded-xl border border-white/10 px-4 text-sm text-white">Exportar JSON</button></div></section><section className="luxia-panel overflow-hidden rounded-3xl"><div className="border-b border-white/10 p-5"><h2 className="font-semibold text-white">Monitor de ejecuciones</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="text-xs uppercase text-zinc-600"><tr><th className="p-4">Módulo</th><th>Motor</th><th>Estado</th><th>Progreso</th><th>Creado</th><th>Error</th></tr></thead><tbody>{executions.map(e=><tr key={e.id} className="border-t border-white/5"><td className="p-4"><p className="text-white">{e.module_key}</p><p className="font-mono text-[10px] text-zinc-700">{e.id}</p></td><td className="text-zinc-400">{e.engine}</td><td className="uppercase text-zinc-400">{e.status}</td><td className="pr-4"><div className="h-2 w-32 overflow-hidden rounded-full bg-white/5"><div className="h-full bg-red-600" style={{width:`${e.progress}%`}}/></div></td><td className="text-zinc-500">{new Date(e.created_at).toLocaleString()}</td><td className="max-w-xs truncate text-red-300">{e.error??"—"}</td></tr>)}</tbody></table></div></section></div>
}
