"use client";

import { AlertTriangle, CheckCircle2, FileJson2, FolderSearch2, LoaderCircle, Upload, WandSparkles } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { browserApiRequest } from "@/lib/api/browser-api";
import type { RuntimeBuilderConfig, RuntimeWorkflowResolution } from "@/types/admin-runtime-builder";

const input="h-11 w-full rounded-xl border border-white/10 bg-black/25 px-3 text-sm text-white outline-none focus:border-red-500/50";
const panel="luxia-panel rounded-3xl p-5";

export function RuntimeImportWizard({onApplied}:{onApplied:(config:RuntimeBuilderConfig)=>void}){
 const [path,setPath]=useState(""); const [workflowFile,setWorkflowFile]=useState<File|null>(null);
 const [report,setReport]=useState<RuntimeWorkflowResolution|null>(null); const [busy,setBusy]=useState(false);
 const [selection,setSelection]=useState({base:true,custom_nodes:true,models:true,dependencies:true,volumes:true});
 const resolve=async()=>{if(!workflowFile||!path.trim())return;setBusy(true);try{
   const workflow=JSON.parse(await workflowFile.text()) as Record<string,unknown>;
   const value=await browserApiRequest<RuntimeWorkflowResolution>("/api/admin/runtime-builder/import/resolve-workflow",{method:"POST",body:JSON.stringify({path,workflow})});
   setReport(value); toast.success("Workflow y entorno resueltos correctamente.");
 }catch(e){toast.error(e instanceof Error?e.message:"No fue posible resolver el workflow.")}finally{setBusy(false)}};
 const apply=async()=>{if(!report)return;setBusy(true);try{
   const value=await browserApiRequest<RuntimeBuilderConfig>("/api/admin/runtime-builder/import/apply",{method:"POST",body:JSON.stringify({report,selection})});
   onApplied(value); toast.success("Runtime mínimo aplicado al Builder.");
 }catch(e){toast.error(e instanceof Error?e.message:"No fue posible aplicar la configuración.")}finally{setBusy(false)}};
 return <div className="space-y-5">
  <section className={panel}><div className="flex items-start gap-4"><div className="flex size-12 items-center justify-center rounded-2xl border border-red-500/20 bg-red-950/25 text-red-400"><WandSparkles/></div><div><h2 className="font-semibold text-white">Dependency Resolver por workflow</h2><p className="mt-2 max-w-4xl text-sm leading-7 text-zinc-500">El workflow es la fuente de verdad. Selecciona tu instalación de Pinokio, Portable, Stability Matrix o Git y carga el JSON. Solo se incluirán los custom nodes, modelos y dependencias que realmente utiliza.</p></div></div></section>
  <section className={panel}><div className="grid gap-4 lg:grid-cols-[1fr_auto]"><label><span className="mb-2 block text-xs font-semibold uppercase tracking-wide text-zinc-500">Ruta de ComfyUI o Pinokio</span><div className="relative"><FolderSearch2 className="absolute left-3 top-3 text-zinc-600" size={18}/><input className={`${input} pl-10`} value={path} onChange={e=>setPath(e.target.value)} placeholder="F:\\pinokio\\api\\comfyui.git\\app"/></div></label><label className="flex min-w-64 cursor-pointer items-center justify-center gap-2 self-end rounded-xl border border-dashed border-white/15 px-4 h-11 text-sm text-zinc-300 hover:border-red-500/30"><Upload size={16}/>{workflowFile?workflowFile.name:"Seleccionar workflow JSON"}<input type="file" accept=".json" className="hidden" onChange={e=>setWorkflowFile(e.target.files?.[0]||null)}/></label></div><button disabled={busy||!path.trim()||!workflowFile} onClick={resolve} className="mt-4 inline-flex h-11 items-center gap-2 rounded-xl bg-red-700 px-4 text-sm font-semibold text-white disabled:opacity-50">{busy?<LoaderCircle size={16} className="animate-spin"/>:<FileJson2 size={16}/>}Analizar workflow y entorno</button></section>
  {report&&<>
   <section className={panel}><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-semibold tracking-[.2em] text-red-500 uppercase">Compatibilidad del runtime</p><h3 className="mt-2 text-3xl font-semibold text-white">{report.summary.compatibility_score}%</h3><p className="mt-1 text-sm text-zinc-500">{report.source_type} · {report.comfyui_path}</p></div>{report.summary.compatibility_score>=80?<CheckCircle2 className="text-emerald-400"/>:<AlertTriangle className="text-amber-400"/>}</div>
   <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{[["Nodos workflow",report.summary.workflow_nodes],["Core resuelto",report.summary.core_classes],["Clases catálogo",report.summary.runtime_catalog_classes],["Custom Nodes",report.summary.required_custom_nodes],["Modelos requeridos",report.summary.required_models],["Modelos faltantes",report.summary.missing_models],["Dependencias",report.summary.python_dependencies],["Tamaño requerido GB",(report.summary.model_size_bytes/1073741824).toFixed(2)]].map(([k,v])=><Metric key={String(k)} label={String(k)} value={String(v)}/>)}</div>
   <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Info label="Python" value={report.python_version}/><Info label="PyTorch" value={report.torch_version}/><Info label="CUDA de Torch" value={report.torch_cuda_version}/><Info label="GPU local" value={report.gpu_name}/></div>
   {report.python_executable&&<p className="mt-3 rounded-xl border border-white/8 bg-black/20 px-3 py-2 text-xs text-zinc-400">Python detectado: {report.python_executable}</p>}</section>
   <div className="grid gap-5 xl:grid-cols-2"><ResultList title="Clases Core resueltas" values={report.core_classes}/><ResultList title="Custom Nodes necesarios" values={report.custom_nodes.map(n=>`${n.name}${n.repository?" · "+n.repository:" · repositorio no detectado"}`)}/><ResultList title="Modelos encontrados" values={report.models.map(m=>`${m.target_path}${m.resolver?` · ${m.resolver.class_type}.${m.resolver.field}`:""}`)}/><ResultList title="Clases no resueltas" values={report.unresolved_classes}/><ResultList title="Modelos faltantes" values={report.missing_models}/></div>
   {report.warnings.length>0&&<section className={panel}><h3 className="flex items-center gap-2 font-semibold text-amber-300"><AlertTriangle size={17}/>Advertencias</h3><div className="mt-3 space-y-2">{report.warnings.map((w,i)=><div key={i} className="rounded-xl border border-amber-500/15 bg-amber-950/10 px-3 py-2 text-xs text-amber-200">{w}</div>)}</div></section>}
   <section className={panel}><h3 className="font-semibold text-white">Aplicar runtime mínimo</h3><div className="mt-4 flex flex-wrap gap-3">{Object.entries(selection).map(([key,value])=><label key={key} className="flex items-center gap-2 rounded-xl border border-white/8 px-3 py-2 text-sm text-zinc-300"><input type="checkbox" checked={value} onChange={e=>setSelection(s=>({...s,[key]:e.target.checked}))}/>{({base:"Base y versiones",custom_nodes:"Custom Nodes requeridos",models:"Modelos requeridos",dependencies:"Dependencias requeridas",volumes:"Volúmenes"} as Record<string,string>)[key]}</label>)}</div><button onClick={apply} disabled={busy||report.missing_models.length>0||report.unresolved_classes.length>0} className="mt-4 inline-flex h-11 items-center gap-2 rounded-xl bg-red-700 px-4 text-sm font-semibold text-white disabled:opacity-50"><CheckCircle2 size={16}/>Aplicar al Runtime Builder</button>{(report.missing_models.length>0||report.unresolved_classes.length>0)&&<p className="mt-3 text-xs text-amber-300">Resuelve los modelos o clases faltantes antes de aplicar para evitar una imagen incompleta.</p>}</section>
  </>}
 </div>
}
function Info({label,value}:{label:string;value:string|null}){return <div className="rounded-xl border border-white/8 bg-black/20 p-3"><p className="text-xs text-zinc-500">{label}</p><p className="mt-1 truncate text-sm text-white">{value||"No detectado"}</p></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-white/8 bg-black/20 p-4"><p className="text-xs text-zinc-500">{label}</p><p className="mt-2 text-xl font-semibold text-white">{value}</p></div>}
function ResultList({title,values}:{title:string;values:string[]}){return <section className={panel}><h3 className="font-semibold text-white">{title} <span className="text-zinc-600">({values.length})</span></h3><div className="mt-3 max-h-72 space-y-1 overflow-auto">{values.length?values.map((v,i)=><div key={`${v}-${i}`} className="rounded-lg border border-white/6 bg-black/15 px-3 py-2 text-xs text-zinc-400">{v}</div>):<div className="text-sm text-zinc-600">Sin elementos</div>}</div></section>}
