"use client";
import { useCallback,useEffect,useState } from "react";
import { Activity,Box,CheckCircle2,CloudUpload,LoaderCircle,Play,Rocket,Square,TriangleAlert } from "lucide-react";
import { toast } from "sonner";
import { browserApiRequest } from "@/lib/api/browser-api";
import type { RuntimeBuild,RuntimeBuildList,RuntimeDockerDiagnostic } from "@/types/admin-runtime-builder";
const button="inline-flex h-10 items-center gap-2 rounded-xl border border-white/10 px-3 text-sm text-zinc-300 disabled:opacity-40";
export function RuntimeBuildPanel(){
 const [items,setItems]=useState<RuntimeBuild[]>([]),[diag,setDiag]=useState<RuntimeDockerDiagnostic|null>(null),[selected,setSelected]=useState<number|null>(null),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const [d,b]=await Promise.all([browserApiRequest<RuntimeDockerDiagnostic>("/api/admin/runtime-builder/diagnostic"),browserApiRequest<RuntimeBuildList>("/api/admin/runtime-builder/builds")]);setDiag(d);setItems(b.items);if(!selected&&b.items[0])setSelected(b.items[0].id);}catch(e){toast.error(e instanceof Error?e.message:"No fue posible cargar builds.")}},[selected]);
 useEffect(()=>{void load();const id=setInterval(()=>void load(),3000);return()=>clearInterval(id)},[load]);
 const act=async(path:string,body?:unknown)=>{setBusy(true);try{await browserApiRequest(path,{method:"POST",body:body?JSON.stringify(body):undefined});await load();toast.success("Operación iniciada.")}catch(e){toast.error(e instanceof Error?e.message:"Operación fallida.")}finally{setBusy(false)}};
 const current=items.find(x=>x.id===selected)??items[0];
 return <div className="space-y-5">
  <section className="luxia-panel grid gap-4 rounded-3xl p-5 md:grid-cols-4"><Metric icon={<Activity/>} label="Docker" value={diag?.docker_available?`Disponible ${diag.docker_version??""}`:"No disponible"}/><Metric icon={<Box/>} label="Buildx" value={diag?.buildx_available?"Disponible":"No disponible"}/><Metric icon={<CloudUpload/>} label="Registro" value={diag?.registry_image??"—"}/><Metric icon={<Rocket/>} label="Imagen activa" value={diag?.active_image??"Sin activar"}/><p className="md:col-span-4 text-xs text-zinc-500">{diag?.message}</p></section>
  <section className="luxia-panel rounded-3xl p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold text-white">Build & Deploy</h2><p className="mt-1 text-sm text-zinc-500">Construye, valida, publica y activa versiones inmutables del runtime.</p></div><button disabled={busy} onClick={()=>void act("/api/admin/runtime-builder/builds",{push_after_build:false})} className="luxia-red-glow inline-flex h-11 items-center gap-2 rounded-xl bg-red-700 px-4 text-sm font-semibold text-white"><Play size={16}/>7. Construir Runtime</button></div></section>
  <div className="grid gap-5 xl:grid-cols-[360px_1fr]"><section className="luxia-panel rounded-3xl p-4"><h3 className="mb-3 text-sm font-semibold text-white">Historial</h3><div className="space-y-2">{items.map(x=><button key={x.id} onClick={()=>setSelected(x.id)} className={`w-full rounded-2xl border p-3 text-left ${selected===x.id?"border-red-500/30 bg-red-950/20":"border-white/8 bg-black/20"}`}><div className="flex items-center justify-between"><span className="font-medium text-white">v{x.version}</span><Status status={x.status}/></div><p className="mt-2 truncate text-xs text-zinc-500">{x.image_tag}</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/5"><div className="h-full bg-red-600" style={{width:`${x.progress}%`}}/></div></button>)}</div></section>
  <section className="luxia-panel rounded-3xl p-5">{!current?<div className="py-16 text-center text-zinc-500">Aún no existen builds.</div>:<><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg font-semibold text-white">{current.image_tag}</h3><p className="mt-1 text-sm text-zinc-500">Fase: {current.phase} · {current.progress}%</p></div><div className="flex flex-wrap gap-2"><button disabled={busy||current.status!=="succeeded"} onClick={()=>void act(`/api/admin/runtime-builder/builds/${current.id}/publish`)} className={button}><CloudUpload size={15}/>8. Publicar</button><button disabled={busy||!current.published} onClick={()=>void act(`/api/admin/runtime-builder/builds/${current.id}/activate`)} className={button}><Rocket size={15}/>9. Activar</button><button disabled={busy||!["pending","building","validating","publishing"].includes(current.status)} onClick={()=>void act(`/api/admin/runtime-builder/builds/${current.id}/cancel`)} className={button}><Square size={14}/>Cancelar</button></div></div>{current.error_message&&<div className="mt-4 rounded-xl border border-red-500/20 bg-red-950/20 p-3 text-sm text-red-300"><TriangleAlert className="mr-2 inline" size={16}/>{current.error_message}</div>}<pre className="mt-5 max-h-[520px] min-h-80 overflow-auto rounded-2xl border border-white/8 bg-black/50 p-4 text-xs leading-6 text-zinc-300">{current.logs||"Esperando logs del constructor..."}</pre></>}</section></div>
 </div>}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-2xl border border-white/8 bg-black/20 p-4"><div className="flex items-center gap-2 text-red-400">{icon}<span className="text-xs uppercase tracking-wider text-zinc-500">{label}</span></div><p className="mt-3 truncate text-sm font-medium text-white">{value}</p></div>}
function Status({status}:{status:RuntimeBuild["status"]}){const ok=["succeeded","published","active"].includes(status);return <span className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-[10px] uppercase ${ok?"bg-emerald-950/40 text-emerald-300":status==="failed"?"bg-red-950/40 text-red-300":"bg-amber-950/40 text-amber-300"}`}>{ok?<CheckCircle2 size={11}/>:status==="building"?<LoaderCircle className="animate-spin" size={11}/>:null}{status}</span>}
