"use client";
import { CheckCircle2, Clipboard, Container, Database, LoaderCircle, Play, Save, Search, TriangleAlert } from "lucide-react";
import { useCallback,useEffect,useMemo,useState } from "react";
import { toast } from "sonner";
import { browserApiRequest } from "@/lib/api/browser-api";
import type { RuntimeContextJob,RuntimeLaunchPreview,RuntimeLaunchSettings,RuntimeModelExportSettings,RuntimeModelVolumeAnalysis,RuntimeModelVolumeExportResponse } from "@/types/admin-runtime-builder";
const input="h-11 w-full rounded-xl border border-white/10 bg-black/25 px-3 text-sm text-white outline-none focus:border-red-500/50";
const defaults:RuntimeLaunchSettings={build_name:"tryon-runtime",image_name:"tryon-runtime:latest",container_name:"tryon-comfyui",host_port:8190,container_port:8188,models_volume:"",workflows_volume:"",output_volume:"",models_mount_path:"/app/ComfyUI/models",workflows_mount_path:"/app/ComfyUI/user/default/workflows",output_mount_path:"/app/ComfyUI/output",gpu_mode:"nvidia",restart_policy:"unless-stopped",extra_arguments:[]};
export function RuntimeMega3Panel(){
 const [volumes,setVolumes]=useState<Array<{name:string}>>([]),[settings,setSettings]=useState<RuntimeModelExportSettings|null>(null),[launch,setLaunch]=useState(defaults),[preview,setPreview]=useState<RuntimeLaunchPreview|null>(null),[analysis,setAnalysis]=useState<RuntimeModelVolumeAnalysis|null>(null),[result,setResult]=useState<RuntimeModelVolumeExportResponse|null>(null),[job,setJob]=useState<RuntimeContextJob|null>(null),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{const [v,s,l]=await Promise.all([browserApiRequest<{items:Array<{name:string}>}>("/api/admin/docker-file-manager/volumes"),browserApiRequest<RuntimeModelExportSettings>("/api/admin/runtime-builder/models-volume/settings"),browserApiRequest<RuntimeLaunchSettings>("/api/admin/runtime-builder/runtime-launch/settings")]);setVolumes(v.items);setSettings(s);setLaunch(l)},[]);
 useEffect(()=>{void load().catch(e=>toast.error(e instanceof Error?e.message:"No se pudo cargar la configuración."))},[load]);
 useEffect(()=>{const id=setTimeout(()=>void browserApiRequest<RuntimeLaunchPreview>("/api/admin/runtime-builder/runtime-launch/preview",{method:"POST",body:JSON.stringify(launch)}).then(setPreview).catch(()=>undefined),250);return()=>clearTimeout(id)},[launch]);
 const patch=<K extends keyof RuntimeModelExportSettings>(k:K,v:RuntimeModelExportSettings[K])=>setSettings(s=>s?{...s,[k]:v}:s); const patchLaunch=<K extends keyof RuntimeLaunchSettings>(k:K,v:RuntimeLaunchSettings[K])=>setLaunch(s=>({...s,[k]:v}));
 const save=async()=>{if(!settings)return;setBusy(true);try{await Promise.all([browserApiRequest("/api/admin/runtime-builder/models-volume/settings",{method:"PUT",body:JSON.stringify(settings)}),browserApiRequest("/api/admin/runtime-builder/runtime-launch/settings",{method:"PUT",body:JSON.stringify(launch)})]);toast.success("Configuración persistida.")}catch(e){toast.error(e instanceof Error?e.message:"No se pudo guardar.")}finally{setBusy(false)}};
 const wait=async(created:RuntimeContextJob)=>{let current=created;while(["queued","running"].includes(current.status)){await new Promise(r=>setTimeout(r,1500));current=await browserApiRequest<RuntimeContextJob>(`/api/admin/runtime-builder/context/jobs/${created.job_id}`);setJob(current)}if(current.status==="failed")throw new Error(current.error||"Exportación fallida.");if(!current.result)throw new Error("Sin resultado.");return current.result as RuntimeModelVolumeExportResponse};
 const analyze=async()=>{if(!settings?.comfyui_path)return toast.error("Indica la ruta de ComfyUI.");setBusy(true);try{setAnalysis(await browserApiRequest<RuntimeModelVolumeAnalysis>("/api/admin/runtime-builder/models-volume/analyze",{method:"POST",body:JSON.stringify({comfyui_path:settings.comfyui_path})}));toast.success("Análisis completado.")}catch(e){toast.error(e instanceof Error?e.message:"Error de análisis.")}finally{setBusy(false)}};
 const run=async()=>{if(!settings?.comfyui_path)return toast.error("Indica la ruta de ComfyUI.");if(settings.destination_type==="docker_volume"&&!settings.docker_volume)return toast.error("Selecciona un volumen.");setBusy(true);setResult(null);try{await save();const created=await browserApiRequest<RuntimeContextJob>("/api/admin/runtime-builder/models-volume/export",{method:"POST",body:JSON.stringify(settings)});setJob(created);setResult(await wait(created));toast.success("Exportación terminada.")}catch(e){toast.error(e instanceof Error?e.message:"Exportación fallida.")}finally{setBusy(false)}};
 if(!settings)return <div className="luxia-panel rounded-3xl p-8 text-zinc-500">Cargando configuración…</div>;
 return <div className="space-y-5">
  <section className="luxia-panel rounded-3xl p-5"><Header icon={<Database/>} eyebrow="Workflow Model Exporter" title="Exportación reproducible de modelos" text="Selecciona carpeta local o volumen Docker, conserva la última configuración y revisa el resumen de cada ejecución."/>
   <div className="grid gap-4 lg:grid-cols-3"><Field label="Ruta local de ComfyUI"><input className={input} value={settings.comfyui_path} onChange={e=>patch("comfyui_path",e.target.value)} placeholder="F:\\ComfyUI"/></Field><Field label="Directorio local de salida"><input className={input} value={settings.output_directory} onChange={e=>patch("output_directory",e.target.value)} placeholder="F:\\runtime_exports"/></Field><Field label="Destino"><select className={input} value={settings.destination_type} onChange={e=>patch("destination_type",e.target.value as RuntimeModelExportSettings["destination_type"])}><option value="local">Carpeta local</option><option value="docker_volume">Volumen Docker</option></select></Field></div>
   {settings.destination_type==="docker_volume"&&<div className="mt-4 grid gap-4 lg:grid-cols-2"><Field label="Volumen Docker"><select className={input} value={settings.docker_volume} onChange={e=>patch("docker_volume",e.target.value)}><option value="">Selecciona…</option>{volumes.map(v=><option key={v.name}>{v.name}</option>)}</select></Field><Field label="Subcarpeta opcional dentro del volumen"><input className={input} value={settings.docker_path} onChange={e=>patch("docker_path",e.target.value)} placeholder="Vacío = raíz del volumen"/><span className="mt-2 block text-xs text-zinc-600">Déjalo vacío para exportar directamente unet/, vae/, loras/ y las demás categorías en la raíz.</span></Field></div>}
   <div className="mt-4 grid gap-3 md:grid-cols-3"><Toggle label="Omitir idénticos" value={settings.skip_identical} set={v=>patch("skip_identical",v)}/><Toggle label="Sobrescribir diferentes" value={settings.overwrite} set={v=>patch("overwrite",v)}/><Toggle label="Calcular SHA-256" value={settings.calculate_sha256} set={v=>patch("calculate_sha256",v)}/></div>
   <div className="mt-5 flex flex-wrap gap-3"><Btn onClick={()=>void save()} disabled={busy}><Save size={16}/>Guardar configuración</Btn><Btn onClick={()=>void analyze()} disabled={busy}><Search size={16}/>Analizar</Btn><button onClick={()=>void run()} disabled={busy} className="inline-flex h-11 items-center gap-2 rounded-xl bg-red-700 px-5 text-sm font-semibold text-white disabled:opacity-50">{busy?<LoaderCircle className="animate-spin" size={16}/>:<Play size={16}/>}Exportar</button></div>
   {job&&busy&&<div className="mt-5"><div className="flex justify-between text-sm"><span className="text-zinc-400">{job.message}</span><b className="text-red-300">{job.progress}%</b></div><div className="mt-2 h-2 rounded-full bg-white/5"><div className="h-2 rounded-full bg-red-700" style={{width:`${job.progress}%`}}/></div></div>}
   {analysis&&<div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Detectados" value={analysis.models_detected}/><Metric label="Encontrados" value={analysis.models_found}/><Metric label="Faltantes" value={analysis.models_missing}/><Metric label="Tamaño" value={bytes(analysis.bytes_total)}/></div>}
  </section>
  <section className="luxia-panel rounded-3xl p-5"><Header icon={<Container/>} eyebrow="Runtime Configuration" title="Configuración de ejecución Docker" text="Define nombres, puertos, GPU y volúmenes. El comando se regenera automáticamente."/>
   <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Text label="Nombre del build" v={launch.build_name} set={v=>patchLaunch("build_name",v)}/><Text label="Nombre de imagen" v={launch.image_name} set={v=>patchLaunch("image_name",v)}/><Text label="Nombre de contenedor" v={launch.container_name} set={v=>patchLaunch("container_name",v)}/><NumberField label="Puerto host" v={launch.host_port} set={v=>patchLaunch("host_port",v)}/><NumberField label="Puerto contenedor" v={launch.container_port} set={v=>patchLaunch("container_port",v)}/><Field label="GPU"><select className={input} value={launch.gpu_mode} onChange={e=>patchLaunch("gpu_mode",e.target.value as RuntimeLaunchSettings["gpu_mode"])}><option value="nvidia">NVIDIA</option><option value="auto">Auto</option><option value="none">Sin GPU</option></select></Field><Volume label="Volumen modelos" v={launch.models_volume} set={v=>patchLaunch("models_volume",v)} list={volumes}/><Volume label="Volumen workflows" v={launch.workflows_volume} set={v=>patchLaunch("workflows_volume",v)} list={volumes}/><Volume label="Volumen outputs" v={launch.output_volume} set={v=>patchLaunch("output_volume",v)} list={volumes}/></div>
   <div className="mt-5 rounded-2xl border border-white/10 bg-black/40 p-4"><div className="mb-3 flex items-center justify-between"><span className="text-xs font-semibold uppercase tracking-wider text-zinc-500">Docker Run Preview</span><button onClick={()=>{void navigator.clipboard.writeText(preview?.command||"");toast.success("Comando copiado.")}} className="inline-flex items-center gap-2 text-sm text-zinc-300"><Clipboard size={15}/>Copiar</button></div><pre className="overflow-x-auto whitespace-pre-wrap text-sm leading-7 text-emerald-300">{preview?.command||"Generando comando…"}</pre></div>
  </section>
  {result&&<Summary result={result}/>} 
 </div>
}
function Header({icon,eyebrow,title,text}:{icon:React.ReactNode;eyebrow:string;title:string;text:string}){return <div className="mb-5 flex gap-4"><div className="flex size-12 items-center justify-center rounded-2xl border border-red-500/20 bg-red-950/20 text-red-400">{icon}</div><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-red-500">{eyebrow}</p><h2 className="mt-1 font-semibold text-white">{title}</h2><p className="mt-1 text-sm text-zinc-500">{text}</p></div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><span className="mb-2 block text-xs font-semibold uppercase tracking-wide text-zinc-500">{label}</span>{children}</label>}
function Text({label,v,set}:{label:string;v:string;set:(v:string)=>void}){return <Field label={label}><input className={input} value={v} onChange={e=>set(e.target.value)}/></Field>}
function NumberField({label,v,set}:{label:string;v:number;set:(v:number)=>void}){return <Field label={label}><input type="number" className={input} value={v} onChange={e=>set(Number(e.target.value))}/></Field>}
function Volume({label,v,set,list}:{label:string;v:string;set:(v:string)=>void;list:Array<{name:string}>}){return <Field label={label}><select className={input} value={v} onChange={e=>set(e.target.value)}><option value="">Sin volumen</option>{list.map(x=><option key={x.name}>{x.name}</option>)}</select></Field>}
function Toggle({label,value,set}:{label:string;value:boolean;set:(v:boolean)=>void}){return <label className="flex items-center justify-between rounded-2xl border border-white/8 bg-black/20 px-4 py-3 text-sm text-zinc-300"><span>{label}</span><input type="checkbox" checked={value} onChange={e=>set(e.target.checked)} className="size-4 accent-red-600"/></label>}
function Btn({children,...p}:React.ButtonHTMLAttributes<HTMLButtonElement>){return <button {...p} className="inline-flex h-11 items-center gap-2 rounded-xl border border-white/10 px-5 text-sm font-semibold text-zinc-200 disabled:opacity-50">{children}</button>}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-2xl border border-white/8 bg-black/20 p-4"><span className="text-xs uppercase text-zinc-500">{label}</span><p className="mt-2 text-lg font-semibold text-white">{value}</p></div>}
function Summary({result}:{result:RuntimeModelVolumeExportResponse}){const r=result as RuntimeModelVolumeExportResponse&{models_overwritten?:number;errors?:number;elapsed_seconds?:number;destination?:unknown};return <section className="luxia-panel rounded-3xl p-5"><div className="flex items-center gap-3"><CheckCircle2 className="text-emerald-400"/><div><h3 className="font-semibold text-white">Resumen de exportación</h3><p className="text-sm text-zinc-500">La operación terminó y el manifiesto quedó generado.</p></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric label="Exportados" value={result.models_copied}/><Metric label="Sobrescritos" value={r.models_overwritten||0}/><Metric label="Omitidos" value={result.models_skipped}/><Metric label="Faltantes" value={result.models_missing}/><Metric label="Errores" value={r.errors||0}/><Metric label="Tiempo" value={`${r.elapsed_seconds||0} s`}/></div>{result.warnings.length>0&&<div className="mt-4 rounded-2xl border border-amber-500/20 bg-amber-950/10 p-4 text-sm text-amber-200"><div className="flex gap-2 font-semibold"><TriangleAlert size={16}/>Advertencias</div>{result.warnings.map((x,i)=><p className="mt-2 text-zinc-400" key={i}>• {x}</p>)}</div>}</section>}
function bytes(v:number){if(!v)return"0 B";const u=["B","KB","MB","GB","TB"],i=Math.min(Math.floor(Math.log(v)/Math.log(1024)),4);return`${(v/1024**i).toFixed(i?2:0)} ${u[i]}`}
