"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { Activity,Box,CheckCircle2,CloudUpload,LoaderCircle,Play,Rocket,Square,Trash2,TriangleAlert } from "lucide-react";
import { toast } from "sonner";
import { browserApiRequest } from "@/lib/api/browser-api";
import type { RuntimeBuild,RuntimeBuildList,RuntimeDockerDiagnostic,RuntimeProject } from "@/types/admin-runtime-builder";
const button="inline-flex h-10 items-center gap-2 rounded-xl border border-white/10 px-3 text-sm text-zinc-300 disabled:opacity-40";
const ACTIVE=new Set(["pending","building","validating","publishing"]);
export function RuntimeBuildPanel(){
 const [items,setItems]=useState<RuntimeBuild[]>([]),[diag,setDiag]=useState<RuntimeDockerDiagnostic|null>(null),[project,setProject]=useState<RuntimeProject|null>(null),[contextDirectory,setContextDirectory]=useState(""),[selected,setSelected]=useState<number|null>(null),[checked,setChecked]=useState<Set<number>>(new Set()),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const [d,b,p]=await Promise.all([browserApiRequest<RuntimeDockerDiagnostic>("/api/admin/runtime-builder/diagnostic"),browserApiRequest<RuntimeBuildList>("/api/admin/runtime-builder/builds"),browserApiRequest<RuntimeProject>("/api/admin/runtime-builder/project")]);setDiag(d);setItems(b.items);setProject(p);setContextDirectory(current=>current||p.export_directory||"");setSelected(current=>current&&b.items.some(item=>item.id===current)?current:b.items[0]?.id??null);setChecked(current=>new Set([...current].filter(id=>b.items.some(item=>item.id===id))));}catch(e){toast.error(e instanceof Error?e.message:"No fue posible cargar builds.")}},[]);
 useEffect(()=>{void load();const id=setInterval(()=>void load(),3000);return()=>clearInterval(id)},[load]);
 const act=async(path:string,body?:unknown)=>{setBusy(true);try{await browserApiRequest(path,{method:"POST",body:body?JSON.stringify(body):undefined});await load();toast.success("Operación completada.")}catch(e){toast.error(e instanceof Error?e.message:"Operación fallida.")}finally{setBusy(false)}};
 const bulk=async(action:"bulk-cancel"|"bulk-delete")=>{const ids=[...checked];if(!ids.length)return;if(action==="bulk-delete"&&!window.confirm(`¿Eliminar ${ids.length} compilación(es) seleccionada(s)? Las activas se omitirán.`))return;await act(`/api/admin/runtime-builder/builds/${action}`,{ids});setChecked(new Set());};
 const current=items.find(x=>x.id===selected)??items[0];
 const allChecked=items.length>0&&items.every(item=>checked.has(item.id));
 const selectedItems=useMemo(()=>items.filter(item=>checked.has(item.id)),[items,checked]);
 return <div className="space-y-5">
  <section className="luxia-panel grid gap-4 rounded-3xl p-5 md:grid-cols-4"><Metric icon={<Activity/>} label="Docker" value={diag?.docker_available?`Disponible ${diag.docker_version??""}`:"No disponible"}/><Metric icon={<Box/>} label="Buildx" value={diag?.buildx_available?"Disponible":"No disponible"}/><Metric icon={<CloudUpload/>} label="Registro" value={diag?.registry_image??"—"}/><Metric icon={<Rocket/>} label="Imagen activa" value={diag?.active_image??"Sin activar"}/><p className="md:col-span-4 text-xs text-zinc-500">{diag?.message}</p></section>
  <section className="luxia-panel rounded-3xl p-5"><div className="mb-4"><label className="text-xs font-semibold uppercase tracking-wide text-zinc-500">Directorio exacto del runtime exportado</label><input value={contextDirectory} onChange={e=>setContextDirectory(e.target.value)} placeholder="C:\\...\\export\\tryon-1.0.0" className="mt-2 h-11 w-full rounded-xl border border-white/10 bg-black/25 px-3 text-sm text-white outline-none focus:border-red-500/50"/><p className="mt-2 text-xs text-zinc-500">Antes del build, el backend comprobará el contexto exportado. Ruta guardada: {project?.export_directory||"ninguna"}</p></div><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold text-white">Build & Deploy</h2><p className="mt-1 text-sm text-zinc-500">Construye, valida, publica y activa versiones inmutables del runtime.</p></div><button disabled={busy} onClick={()=>void act("/api/admin/runtime-builder/builds",{push_after_build:false,context_directory:contextDirectory.trim()||project?.export_directory||null})} className="luxia-red-glow inline-flex h-11 items-center gap-2 rounded-xl bg-red-700 px-4 text-sm font-semibold text-white"><Play size={16}/>7. Construir Runtime</button></div></section>
  <section className="luxia-panel flex flex-wrap items-center justify-between gap-3 rounded-3xl p-4"><label className="flex items-center gap-3 text-sm text-zinc-300"><input type="checkbox" checked={allChecked} onChange={()=>setChecked(allChecked?new Set():new Set(items.map(item=>item.id)))} className="size-4 accent-red-600"/>Seleccionar todo <span className="text-zinc-600">({checked.size})</span></label><div className="flex flex-wrap gap-2"><button disabled={busy||!selectedItems.some(item=>ACTIVE.has(item.status))} onClick={()=>void bulk("bulk-cancel")} className={button}><Square size={14}/>Cancelar seleccionadas</button><button disabled={busy||checked.size===0} onClick={()=>void bulk("bulk-delete")} className={button}><Trash2 size={15}/>Eliminar seleccionadas</button></div></section>
  <div className="grid gap-5 xl:grid-cols-[360px_1fr]"><section className="luxia-panel rounded-3xl p-4"><h3 className="mb-3 text-sm font-semibold text-white">Historial</h3><div className="space-y-2">{items.map(x=><div key={x.id} className={`flex items-start gap-3 rounded-2xl border p-3 ${selected===x.id?"border-red-500/30 bg-red-950/20":"border-white/8 bg-black/20"}`}><input type="checkbox" checked={checked.has(x.id)} onChange={()=>setChecked(current=>{const next=new Set(current);if(next.has(x.id))next.delete(x.id);else next.add(x.id);return next})} className="mt-1 size-4 shrink-0 accent-red-600"/><button onClick={()=>setSelected(x.id)} className="min-w-0 flex-1 text-left"><div className="flex items-center justify-between"><span className="font-medium text-white">v{x.version}</span><Status status={x.status}/></div><p className="mt-2 truncate text-xs text-zinc-500">{x.image_tag}</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/5"><div className="h-full bg-red-600" style={{width:`${x.progress}%`}}/></div></button></div>)}</div></section>
  <section className="luxia-panel rounded-3xl p-5">{!current?<div className="py-16 text-center text-zinc-500">Aún no existen builds.</div>:<><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg font-semibold text-white">{current.image_tag}</h3><p className="mt-1 text-sm text-zinc-500">Fase: {current.phase} · {current.progress}%</p></div><div className="flex flex-wrap gap-2"><button disabled={busy||current.status!=="succeeded"} onClick={()=>void act(`/api/admin/runtime-builder/builds/${current.id}/publish`)} className={button}><CloudUpload size={15}/>8. Publicar</button><button disabled={busy||!current.published} onClick={()=>void act(`/api/admin/runtime-builder/builds/${current.id}/activate`)} className={button}><Rocket size={15}/>9. Activar</button><button disabled={busy||!ACTIVE.has(current.status)} onClick={()=>void act(`/api/admin/runtime-builder/builds/${current.id}/cancel`)} className={button}><Square size={14}/>Cancelar</button></div></div>{current.error_message&&<div className="mt-4 rounded-xl border border-red-500/20 bg-red-950/20 p-3 text-sm text-red-300"><TriangleAlert className="mr-2 inline" size={16}/>{current.error_message}</div>}<pre className="mt-5 max-h-[520px] min-h-80 overflow-auto rounded-2xl border border-white/8 bg-black/50 p-4 text-xs leading-6 text-zinc-300">{current.logs||"Esperando logs del constructor..."}</pre></>}</section></div>
 </div>}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-2xl border border-white/8 bg-black/20 p-4"><div className="flex items-center gap-2 text-red-400">{icon}<span className="text-xs uppercase tracking-wider text-zinc-500">{label}</span></div><p className="mt-3 truncate text-sm font-medium text-white">{value}</p></div>}
function Status({status}:{status:RuntimeBuild["status"]}){const ok=["succeeded","published","active"].includes(status);return <span className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-[10px] uppercase ${ok?"bg-emerald-950/40 text-emerald-300":status==="failed"?"bg-red-950/40 text-red-300":"bg-amber-950/40 text-amber-300"}`}>{ok?<CheckCircle2 size={11}/>:status==="building"?<LoaderCircle className="animate-spin" size={11}/>:null}{status}</span>}
