"use client";

import { CheckCircle2, FileArchive, FileJson2, FolderSearch2, LoaderCircle, RefreshCcw, Upload, WandSparkles } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { browserApiRequest } from "@/lib/api/browser-api";
import type { RuntimeBuilderConfig, RuntimeImportReport, RuntimeWorkflowAnalysis } from "@/types/admin-runtime-builder";

const input="h-11 w-full rounded-xl border border-white/10 bg-black/25 px-3 text-sm text-white outline-none focus:border-red-500/50";
const panel="luxia-panel rounded-3xl p-5";

export function RuntimeImportWizard({onApplied}:{onApplied:(config:RuntimeBuilderConfig)=>void}){
 const [path,setPath]=useState(""); const [report,setReport]=useState<RuntimeImportReport|null>(null); const [analysis,setAnalysis]=useState<RuntimeWorkflowAnalysis|null>(null); const [busy,setBusy]=useState(false);
 const [selection,setSelection]=useState({base:true,custom_nodes:true,models:true,dependencies:false,volumes:true});
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);try{await fn()}catch(e){toast.error(e instanceof Error?e.message:"No fue posible completar la importación.")}finally{setBusy(false)}};
 const scan=()=>run(async()=>{const value=await browserApiRequest<RuntimeImportReport>("/api/admin/runtime-builder/import/scan-path",{method:"POST",body:JSON.stringify({path,include_all_models:true})});setReport(value);toast.success("Instalación de ComfyUI analizada.")});
 const upload=(file:File)=>run(async()=>{const form=new FormData();form.append("file",file);const value=await browserApiRequest<RuntimeImportReport>("/api/admin/runtime-builder/import/upload",{method:"POST",body:form});setReport(value);toast.success("Inventario importado.")});
 const workflow=(file:File)=>run(async()=>{const json=JSON.parse(await file.text()) as Record<string,unknown>;const value=await browserApiRequest<RuntimeWorkflowAnalysis>("/api/admin/runtime-builder/import/analyze-workflow",{method:"POST",body:JSON.stringify({workflow:json,report})});setAnalysis(value);toast.success("Workflow analizado.")});
 const apply=()=>run(async()=>{if(!report)return;const value=await browserApiRequest<RuntimeBuilderConfig>("/api/admin/runtime-builder/import/apply",{method:"POST",body:JSON.stringify({report,selection})});onApplied(value);toast.success("Configuración aplicada al Runtime Builder.")});
 return <div className="space-y-5">
  <section className={panel}><div className="flex items-start gap-4"><div className="flex size-12 items-center justify-center rounded-2xl border border-red-500/20 bg-red-950/25 text-red-400"><WandSparkles/></div><div><h2 className="font-semibold text-white">Importar entorno real de ComfyUI</h2><p className="mt-2 max-w-3xl text-sm leading-7 text-zinc-500">Compatible con Pinokio, Stability Matrix, Portable, Git y carpetas personalizadas. El Backend debe poder leer la ruta local; si corre en otra máquina, usa un ZIP de inventario.</p></div></div></section>
  <div className="grid gap-5 xl:grid-cols-2">
   <section className={panel}><h3 className="flex items-center gap-2 font-semibold text-white"><FolderSearch2 size={18} className="text-red-400"/>Escanear carpeta</h3><p className="mt-2 text-sm text-zinc-500">Puedes seleccionar la carpeta de Pinokio, su carpeta api o directamente ComfyUI.</p><div className="mt-4 flex gap-2"><input className={input} value={path} onChange={e=>setPath(e.target.value)} placeholder="F:\\pinokio\\api\\comfyui.git\\app"/><button disabled={busy||!path.trim()} onClick={scan} className="inline-flex h-11 items-center gap-2 rounded-xl bg-red-700 px-4 text-sm font-semibold text-white disabled:opacity-50">{busy?<LoaderCircle size={16} className="animate-spin"/>:<RefreshCcw size={16}/>}Analizar</button></div></section>
   <section className={panel}><h3 className="flex items-center gap-2 font-semibold text-white"><FileArchive size={18} className="text-red-400"/>Importar ZIP de inventario</h3><p className="mt-2 text-sm text-zinc-500">No subas checkpoints ni secretos. Acepta el paquete de reportes o una copia ligera de la estructura de ComfyUI.</p><label className="mt-4 flex h-11 cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed border-white/15 text-sm text-zinc-300 hover:border-red-500/30"><Upload size={16}/>Seleccionar ZIP<input type="file" accept=".zip" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}}/></label></section>
  </div>
  {report&&<><section className={panel}><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-semibold tracking-[.2em] text-red-500 uppercase">Instalación detectada</p><h3 className="mt-2 text-xl font-semibold text-white">{report.source_type}</h3><p className="mt-1 text-sm text-zinc-500">{report.comfyui_path||"Inventario remoto"}</p></div><CheckCircle2 className="text-emerald-400"/></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["Custom Nodes",report.summary.custom_nodes],["Con Git",report.summary.git_nodes],["Modelos",report.summary.models],["Dependencias",report.summary.python_dependencies],["Modelos GB",(report.summary.model_size_bytes/1073741824).toFixed(2)]].map(([k,v])=><div key={String(k)} className="rounded-2xl border border-white/8 bg-black/20 p-4"><p className="text-xs text-zinc-500">{k}</p><p className="mt-2 text-xl font-semibold text-white">{v}</p></div>)}</div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Info label="Python" value={report.python_version}/><Info label="PyTorch" value={report.torch_version}/><Info label="CUDA de Torch" value={report.torch_cuda_version}/><Info label="GPU local" value={report.gpu_name}/></div>{report.warnings.length>0&&<div className="mt-4 space-y-2">{report.warnings.slice(0,20).map((w,i)=><div key={i} className="rounded-xl border border-amber-500/15 bg-amber-950/10 px-3 py-2 text-xs text-amber-300">{w}</div>)}</div>}</section>
  <section className={panel}><h3 className="font-semibold text-white">Selecciona qué importar</h3><div className="mt-4 flex flex-wrap gap-3">{Object.entries(selection).map(([key,value])=><label key={key} className="flex items-center gap-2 rounded-xl border border-white/8 px-3 py-2 text-sm text-zinc-300"><input type="checkbox" checked={value} onChange={e=>setSelection(s=>({...s,[key]:e.target.checked}))}/>{({base:"Base ComfyUI/Python/CUDA",custom_nodes:"Custom Nodes",models:"Modelos",dependencies:"pip freeze completo",volumes:"Volúmenes"} as Record<string,string>)[key]}</label>)}</div><p className="mt-3 text-xs text-zinc-500">Por seguridad, “pip freeze completo” viene desactivado: suele incluir dependencias del entorno local que no deben fijarse en Docker.</p><button onClick={apply} disabled={busy} className="mt-4 inline-flex h-11 items-center gap-2 rounded-xl bg-red-700 px-4 text-sm font-semibold text-white"><CheckCircle2 size={16}/>Aplicar al Runtime Builder</button></section></>}
  <section className={panel}><h3 className="flex items-center gap-2 font-semibold text-white"><FileJson2 size={18} className="text-red-400"/>Analizar workflow</h3><p className="mt-2 text-sm text-zinc-500">Carga el JSON visual o API de ComfyUI para detectar clases de nodos y modelos referenciados.</p><label className="mt-4 inline-flex h-11 cursor-pointer items-center gap-2 rounded-xl border border-white/10 px-4 text-sm text-zinc-300"><Upload size={16}/>Seleccionar workflow JSON<input type="file" accept=".json" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void workflow(f)}}/></label>{analysis&&<div className="mt-5 grid gap-4 lg:grid-cols-3"><Metric label="Nodos" value={analysis.summary.nodes}/><Metric label="Clases únicas" value={analysis.summary.unique_classes}/><Metric label="Modelos referenciados" value={analysis.summary.referenced_models}/><List title="Modelos encontrados" values={analysis.referenced_models}/><List title="Clases custom detectadas" values={analysis.custom_node_classes}/><List title="Posibles nodos faltantes" values={analysis.potentially_missing_nodes}/></div>}</section>
 </div>
}
function Info({label,value}:{label:string;value:string|null}){return <div className="rounded-xl border border-white/8 bg-black/20 p-3"><p className="text-xs text-zinc-500">{label}</p><p className="mt-1 truncate text-sm text-white">{value||"No detectado"}</p></div>}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-white/8 bg-black/20 p-4"><p className="text-xs text-zinc-500">{label}</p><p className="mt-2 text-2xl font-semibold text-white">{value}</p></div>}
function List({title,values}:{title:string;values:string[]}){return <div className="rounded-2xl border border-white/8 bg-black/20 p-4"><p className="text-sm font-semibold text-white">{title}</p><div className="mt-3 max-h-48 space-y-1 overflow-auto text-xs text-zinc-400">{values.length?values.map(v=><div key={v}>{v}</div>):<div>Sin resultados</div>}</div></div>}
