"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { CheckCircle2,Coins,LoaderCircle,Pencil,Plus,RefreshCcw,Search,Tags,TriangleAlert } from "lucide-react";
import { toast } from "sonner";
import { BillingCouponEditor } from "@/components/backoffice/billing/billing-coupon-editor";
import { browserApiRequest } from "@/lib/api/browser-api";
import { AdminPagination } from "@/components/backoffice/admin-pagination";
import type { BillingCouponListResponse,BillingCouponResponse } from "@/types/admin-pricing-coupons";
type BooleanFilter="all"|"true"|"false";
const PAGE_SIZE=50;

function appliesToLabel(appliesTo: BillingCouponResponse["applies_to"]): string {
 const labels=appliesTo.map(scope=>scope==="token_packages"?"Paquetes de tokens":"Compra libre de tokens");
 return labels.length>0?labels.join(" · "):"Sin destino configurado";
}

export default function CouponsPage(){
 const [response,setResponse]=useState<BillingCouponListResponse>({items:[],total:0,skip:0,limit:PAGE_SIZE}); const [page,setPage]=useState(0); const [search,setSearch]=useState(""); const [debouncedSearch,setDebouncedSearch]=useState(""); const [active,setActive]=useState<BooleanFilter>("all"); const [editing,setEditing]=useState<BillingCouponResponse|null|undefined>(undefined); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [action,setAction]=useState<string|null>(null);
 const query=useMemo(()=>{const p=new URLSearchParams({skip:String(page*PAGE_SIZE),limit:String(PAGE_SIZE)});if(debouncedSearch.trim())p.set("search",debouncedSearch.trim());if(active!=="all")p.set("is_active",active);return p.toString();},[debouncedSearch,active,page]);
 const load=useCallback(async()=>{setLoading(true);setError(null);try{setResponse(await browserApiRequest<BillingCouponListResponse>(`/api/admin/billing-coupons?${query}`));}catch(e){setError(e instanceof Error?e.message:"No fue posible cargar los cupones.");}finally{setLoading(false);}},[query]); useEffect(()=>{void load();},[load]); useEffect(()=>{const id=window.setTimeout(()=>setDebouncedSearch(search),350);return()=>window.clearTimeout(id)},[search]);
 const saved=(coupon:BillingCouponResponse)=>{setResponse(c=>({...c,total:c.items.some(x=>x.id===coupon.id)?c.total:c.total+1,items:c.items.some(x=>x.id===coupon.id)?c.items.map(x=>x.id===coupon.id?coupon:x):[coupon,...c.items]}));setEditing(undefined);};
 const toggle=async(c:BillingCouponResponse)=>{setAction(`a-${c.id}`);try{saved(await browserApiRequest<BillingCouponResponse>(`/api/admin/billing-coupons/${c.id}/${c.is_active?"deactivate":"activate"}`,{method:"POST"}));}catch(e){toast.error(e instanceof Error?e.message:"No fue posible cambiar el estado.");}finally{setAction(null);}};
 const discount=(c:BillingCouponResponse)=>`${c.percentage_off??0}% de la ganancia`;
 return <div><section className="luxia-panel overflow-hidden rounded-3xl"><div className="border-b border-white/6 p-6"><div className="flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between"><div className="flex items-start gap-4"><div className="luxia-red-glow flex size-14 items-center justify-center rounded-2xl border border-red-500/20 bg-red-950/25 text-red-400"><Tags size={24}/></div><div><p className="text-[10px] font-semibold tracking-[0.2em] text-red-500 uppercase">Comercial</p><h1 className="mt-2 text-2xl font-semibold text-white">Cupones</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-zinc-600">Promociones exclusivas para paquetes de tokens y compra libre de tokens. Nunca se aplican a planes ni generaciones.</p></div></div><button onClick={()=>void load()} className="inline-flex h-11 items-center gap-2 rounded-xl border border-white/8 px-4 text-sm text-zinc-400"><RefreshCcw size={16}/>Actualizar</button></div></div></section>
 <section className="luxia-panel mt-5 overflow-hidden rounded-3xl"><div className="border-b border-white/6 p-5"><div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div><h2 className="font-semibold text-white">Catálogo de cupones</h2><p className="mt-1 text-xs text-zinc-600">{response.total} cupones registrados</p></div><div className="flex flex-col gap-3 sm:flex-row"><label className="relative"><Search size={16} className="absolute top-1/2 left-4 -translate-y-1/2 text-zinc-700"/><input value={search} onChange={e=>{setSearch(e.target.value);setPage(0)}} placeholder="Buscar cupón..." className="h-11 rounded-xl border border-white/8 bg-black/30 pr-4 pl-11 text-sm text-white"/></label><select value={active} onChange={e=>{setActive(e.target.value as BooleanFilter);setPage(0)}} className="h-11 rounded-xl border border-white/8 bg-[#09090a] px-4 text-sm text-zinc-300"><option value="all">Cualquier estado</option><option value="true">Activos</option><option value="false">Inactivos</option></select><button onClick={()=>setEditing(null)} className="luxia-red-glow inline-flex h-11 items-center gap-2 rounded-xl bg-red-700 px-4 text-sm font-semibold text-white"><Plus size={16}/>Nuevo cupón</button></div></div></div>
 {loading&&<div className="flex min-h-64 items-center justify-center"><LoaderCircle className="animate-spin text-red-500"/></div>}{!loading&&error&&<div className="m-5 flex gap-3 rounded-2xl border border-red-500/15 bg-red-950/15 p-5 text-red-300"><TriangleAlert size={18}/>{error}</div>}{!loading&&!error&&<div className="grid gap-5 p-5 lg:grid-cols-2 2xl:grid-cols-3">{response.items.map(c=><article key={c.id} className="rounded-3xl border border-white/7 bg-black/20 p-6"><div className="flex justify-between gap-4"><div><p className="font-mono text-lg font-semibold text-white">{c.code}</p><p className="mt-1 text-xs text-zinc-600">{c.name}</p></div><CheckCircle2 size={17} className="text-emerald-400"/></div><p className="mt-5 text-3xl font-semibold text-red-300">{discount(c)}</p><p className="mt-2 text-xs text-zinc-600">{appliesToLabel(c.applies_to)}</p><div className="mt-5 grid grid-cols-1 gap-2"><button onClick={()=>setEditing(c)} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl border border-white/8 text-sm text-zinc-400"><Pencil size={15}/>Editar</button><button onClick={()=>void toggle(c)} disabled={action===`a-${c.id}`} className="inline-flex h-10 items-center justify-center gap-2 rounded-xl border border-amber-500/15 text-sm text-amber-300"><Coins size={15}/>{c.is_active?"Desactivar":"Activar"}</button></div></article>)}</div>}<AdminPagination page={page} pageSize={PAGE_SIZE} total={response.total} loading={loading} label="cupones" onPageChange={setPage}/></section>
 {editing!==undefined&&<BillingCouponEditor coupon={editing} onClose={()=>setEditing(undefined)} onSaved={saved}/>}</div>;
}
